### ISSUE TITLE
handling a large number of polygons

### ISSUE THREAD

**Issue by geoHeil** [DataSystemsLab/GeoSpark#103]
I have polygons which look like this https://gis.stackexchange.com/questions/242710/polygonize-raster-and-shrink-number-of-polygons and there are lots of them.

Usually  a spatial join will lookup the bounding box and then for each matching /filtered pair validate the within constraint. As I have a large number of polygons and so far could not find this 2 step process in geospark's code I wonder if this could be integrated easily in order to increase performance as discussed in https://github.com/DataSystemsLab/GeoSpark/issues/91

So far I could only see that objects are

- spatially partitioned
- looked up from the R tree

I wonder if this pruning is already implemented (lookup only of the envelopes, then validate within constraint) or if it could easily be added.

**Comment by jiayuasu** [comment]
@geoHeil 
Hi Geoheil,
When using R-Tree, I do use MBR to filter useless polygon and then calculate the intersection relation using the real boundary.

The code is here: https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/joinJudgement/GeometryByPolygonJudgementUsingIndex.java#L75-L81

**Comment by viswanatharv** [comment]
@jiayuasu 
The above link is not working. Can you please provide the correct link?

Thanks
Vish
