### ISSUE TITLE
Questions - EPSG conversion

### ISSUE THREAD

**Issue by anto** [DataSystemsLab/GeoSpark#109]
Hello Everybody,

I have a simple table generated by createOrReplaceTempView of the processing in Zeppelin 0.7.2 and Spark 2.1.1. It contains X, Y and Value. The X and Y are coordinate in EPSG 32722. When I want to convert such coordinate into EPSG 4326, I usually export the table into CSV file, use a tool to convert the coordinate and then import it back into a new table.

It looks like I can do that process directly in Zeppelin and Spark using GeoSpark, especially after the update on 0.8.1 for the particular function that I am after, However, until now I cannot figure out how to implement that using GeoSpark, after a lot of trying following the examples.

I think my problem is very basic. That is I still don't understand the syntax of the functions for that. Does anybody have any hints please? Any example codes in using existing RDD perhaps?

Thanks a lot in advance.

Kind regards,

Anto

**Comment by jiayuasu** [comment]
@anto , have you successfully got a SpatialRDD using SpatialRDD constructor?

If so, please use 
```
public boolean CRSTransform(String sourceEpsgCRSCode, String targetEpsgCRSCode)
```
to do CRSTransformation on your spatialRDD.

Pseudo code:
```
PointRDD myPointRDD = new PointRDD(...)
myPointRDD.CRSTransform("epsg:32722","epsg:4326")
```

After that, you can persist it onto disk.
Pseudo code to store as TSV:
```
myPointRDD.rawSpatialRDD.saveAsTextFile(...)
```

Pseudo code to store as GeoJSON:
```
myPointRDD.saveAsGeoJSON(...)
```

**Comment by anto** [comment]
Hello jiayuasu,

Thanks a lot for the hints. I have been away so I am sorry that I could not respond back earlier.

I can indeed manage load CSV file, convert EPSG and save it back into TSV file. The example of my results is as below:

```
CSV Input Data with EPSG: 32772
780530,9839470,783767
780710,9840510,22004

Conversion result to EPSG: 4326
POINT (-1.4509475921881358 -48.47896284047234)	780530,9839470,783767
POINT (-1.4415458115407216 -48.47735667412911)	780710,9840510,22004
```
However, what I have been looking for is the processing without involving files, as the input data might be quite big. So I basically would like to load Spark RDD or Hive table into SpatialRDD, convert the EPSG and store the result back into different Spark RDD or Hive table.

I am not sure how to achieve that as it seems the only way to create SpatialRDD is load the data from a file, e.g. PointRDDInputLocation. Do you have any suggestion on this?

Thanks a lot in advance for your help.

Kind regards,

Anto
