### ISSUE TITLE
Does GeoSpark have the function of changing the attribute value and adding attribute fields of each feature in Shapefile, in addition to spatial coordinates 

### ISSUE THREAD

**Issue by Fali1009** [DataSystemsLab/GeoSpark#111]

**Comment by jiayuasu** [comment]
GeoSpark now only supports reading shapes (in shx) and attributes (in dbf) from shapefiles (including shx and dbf) and doesn't support writing data back to shapefile. However, GeoSpark can write data to WKT and GeoJSON.



1. After successfully loading shapefile into GeoSpark, every SpatialRDD has a method called SaveAsGeoJSON. You can call it like this:

myPointRDD.SaveAsGeoJSON(Disk/HDFS/OtherLocation);

GeoSpark JavaDoc has specified all APIs in GeoSpark: http://www.public.asu.edu/~jiayu2/geospark/javadoc/0.8.1/

2. After successfully loading shapefile into GeoSpark, non-spatial attributes from DBF are merged to one big String and stored in UserData in each Spatial Object of SpatialRDD. 

The RDD looks like this: 

coordinate\tPhone1\tCountry1
coordinate\tPhone2\tCountry2
coordinate\tPhone3\tCountry3
coordinate\tPhone4\tCountry4


For example, after the loading, I want to filter out the objects that contain "phoneNumber:1234". The pseudo code is like this:

```
JavaRDD<Point> newSpatialRDD = myPointRDD.rawSpatialRDD.filter(
new FilterFunction(String s)
{
	List<String> attributes = s.split("\t");
	// Use "Tab" character to split the attributes because we merge them into one String
	if(attributes[0].contains("1234"))
	{
  		return true;
	}
	else
	{
		return false;
	}
}));
```
