### ISSUE TITLE
Does the JoinQuery.DistanceJoinQuery not support LineStringRDD with PointRDD?

### ISSUE THREAD

**Issue by cfu1** [DataSystemsLab/GeoSpark#125]
I tried to run the
val result = JoinQuery.DistanceJoinQuery(geojson_line, queryRDD, true, true);
to have a spatial join of a set of lines and points, but got the error below:
java.lang.ClassCastException: com.vividsolutions.jts.geom.Point cannot be cast to com.vividsolutions.jts.geom.LineString

I'm new to the jts packege. Such distance is supported by python packages like Shapely. Any suggestions?

**Comment by cfu1** [comment]
I tried to run the 
val result = JoinQuery.DistanceJoinQuery(geojson_line, queryRDD, true, true);
to have a spatial join of a set of lines and points, but got the error below:
java.lang.ClassCastException: com.vividsolutions.jts.geom.Point cannot be cast to com.vividsolutions.jts.geom.LineString

I'm new to the jts packege. Such distance is supported by python packages like Shapely. Any suggestions?

**Comment by jiayuasu** [comment]
@cfu1 Sorry for the late reply. Currently, DistanceJoin API only supports same type object join. However, we are working on a new release to fix this. All these problems should be solved in version 0.9.0 stable release.
