### ISSUE TITLE
Keep non-spatial attributes during SRDD computation

### ISSUE THREAD

**Issue by jiayuasu** [DataSystemsLab/GeoSpark#13]
User should have the freedom to decide whether keep the non-spatial attributes during SRDD computation instead of dropping the non-spatial attributes directly. It is hard for users to recover the dropped attributes afterwards.

**Comment by gaufung** [comment]
In JTS or plus, every geometry has those two methods: getUserData and setUserData, which can store non-spatial attributes.  BTW, I have read your paper, in which you do not take into consideration  of ellipsoid when you process the longitude and latitude. I think projection is a better choice when you process gis problem.

**Comment by jiayuasu** [comment]
Thanks for your comment! It is very helpful. We may also consider the ellipsoid in the future.

**Comment by jiayuasu** [comment]
This problem has been solved. Now JTSplus spatial objects all carry the original user input data. See this answer: https://github.com/DataSystemsLab/GeoSpark/issues/25.
