### ISSUE TITLE
Correlation Methods and Java Examples

### ISSUE THREAD

**Issue by samchorlton** [DataSystemsLab/GeoSpark#14]
Hi,

I was reading through the functionality provided by GeoSpark and I am really interested in what is on offer. I was especially interested in the "Spatial aggregation, spatial autocorrelation and spatial co-location" methods. But could not find any details on how these methods have been implemented. 

There appeared to be reference to these already being implemented as examples in "app" folder but I was unable to locate this.

Any information would be greatly appreciated.

Sam

**Comment by jiayuasu** [comment]
Hi,

Java example of GeoSpark is available here: https://github.com/DataSystemsLab/GeoSpark/blob/master/src/main/java/org/datasyslab/geospark/showcase/Example.java

Thanks,
Jia
