### ISSUE TITLE
Missing values when reading Shapefile

### ISSUE THREAD

**Issue by thekannman** [DataSystemsLab/GeoSpark#141]
I'm trying to read in the shapefile from http://openstreetmapdata.com/data/water-polygons. The one I'm using is the first option under the downloads section (direct link: http://data.openstreetmapdata.com/water-polygons-split-4326.zip).

This file should have over 40,000 polygons, which I have confirmed by using shapefile explorer. However, when I read it into GeoSpark
```
val shp = new ShapefileRDD(sc,"water-polygons-split-4326/")
shp.count
```
The count is 9226 rather than 40+ thousand. Visualization of the output with GeoSparkViz also shows a lack of the last 30K+ polygons.

**Comment by jiayuasu** [comment]
@zongsizhang Zongsi, please verify this.

**Comment by zongsizhang** [comment]
@thekannman Hi, thanks for reporting this, I've checked this .shp file and find out that the described length of .shp file in its header is wrong and it's about 1/4 of the file size. I'll try to import .shx file to fix this problem. @jiayuasu

**Comment by zongsizhang** [comment]
@jiayuasu @thekannman I've started a new PR that solve this problem. #149
