### ISSUE TITLE
Can GeoSpark apply to remote sensing data?

### ISSUE THREAD

**Issue by bearxiong3** [DataSystemsLab/GeoSpark#147]
Hello!
I have big amount of RS image data in "TIFF" format.
I need compute with these RS data effectively and rapidly.
Can I realize this target with GeoSpark?
Thank you for your attention!

**Comment by jiayuasu** [comment]
Hi @bearxiong3 

We currently cannot directly load TIFF format. But if you can convert it to csv, tsv, wkt, GeoJSON, shapefile, then GeoSpark can handle that.

Thanks,
Jia

**Comment by bearxiong3** [comment]
Hi @jiayuasu 
Thank you for your patient answer! I got it.
