### ISSUE TITLE
GeoSpark kryo serializer and GeoSpark viz conflict

### ISSUE THREAD

**Issue by jiayuasu** [DataSystemsLab/GeoSpark#154]
If a project contains both GeoSpark core and viz and open GeoSpark kryo serializer, GeoSpark viz will throw an exception called "assertion failed: image == null!"

To solve this problem, remove the following sentences from your code which starts GeoSpark kryo serializer:
sparkConf.set("spark.serializer", classOf[KryoSerializer].getName)
sparkConf.set("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)

The reason that leads to this conflict is still under investigation.

**Comment by geoHeil** [comment]
`GeoSparkKryoRegistrator ` does not seem to be in the exported father from maven central - at lest not for SBT.
