### ISSUE TITLE
Precompiled jar for geospark

### ISSUE THREAD

**Issue by omkarkaptan** [DataSystemsLab/GeoSpark#17]
The repository has a maven project for GeoSpark. Is there a pre-compiled jar of this project available in the repository or anywhere else that can be consumed directly? Otherwise the project will have to be built manually before every use.

**Comment by jiayuasu** [comment]
Hi,

Please refer to GeoSpark repository "release" tag: https://github.com/DataSystemsLab/GeoSpark/releases

We provide pre-compiled full jar package for users. You can directly add it to your Scala/Java project or use it in Spark Scale shell.

Thanks,
Jia
