### ISSUE TITLE
不支持中文。It doesn't read Chinese in the shape file correctly. Can you add the UTF-8 support?

### ISSUE THREAD

**Issue by marcomeng** [DataSystemsLab/GeoSpark#190]

**Comment by jiayuasu** [comment]
@marcomeng Can you point me to your shapefile? Or can you send me your shapefile? My email is jiayu2@asu.edu

**Comment by marcomeng** [comment]
sent the mail, thanks.

**Comment by jiayuasu** [comment]
@marcomeng Solved. See PR https://github.com/DataSystemsLab/GeoSpark/pull/192

This PR is already pushed to GeoSpark 1.1.0-SNAPSHOT. To use GeoSpark SNAPSHOT version, please read [1].

To read your shapefile, add the following line before your shapefile reader.
```
System.setProperty("geospark.global.charset","utf8")
```
 For instance,

```
System.setProperty("geospark.global.charset","utf8")
spatialRDD.rawSpatialRDD = ShapefileReader.readToGeometryRDD(sparkSession.sparkContext, "/PATH/realestate_mall_polygon/")
```

[1] GeoSpark Maven coordinates: https://github.com/DataSystemsLab/GeoSpark/wiki/GeoSpark-All-Modules-Maven-Central-Coordinates

**Comment by marcomeng** [comment]
Thanks a lot! I just tried, it works!

**Comment by yijialee** [comment]
now you should write like this:
```
System.setProperty("sedona.global.charset","utf8")
```
