### ISSUE TITLE
ShapefileReader Does not Provide Any Metadata...Its Usage is very limited.

### ISSUE THREAD

**Issue by paulzwu** [DataSystemsLab/GeoSpark#191]
This class does not provide any metadata support?...for example, if I use it to read US states's shape file, I'll get a collection of Polygon and Mutlipolygon,  I even don't know which shape is for which state,  how can I use it? Any help will be appreciated. It also may need to modify Adapter to provide the metadata for the SQL part.

**Comment by jiayuasu** [comment]
@paulzwu 
GeoSpark shapefile reader can read metadata in DBF file.

If you use GeoSpark RDD API, the metadata is stored in UserData attribute in each geometry. Use aPolygon.getUserData to retrieve it.

If you use GeoSpark SQL API, the example clearly shows how to use shapefile to GeoSparkSQL.

**Comment by paulzwu** [comment]
Thanks.  I found  an example (from GeoSpark)  which shows using org.geotools.data.DataStore to read shapefile, then  I can use org.opengis.feature.Feature to get the other data.  From that point, I can transform the data into a table with shape and other fields (features) I need.
