### ISSUE TITLE
Spark 2.3 UDF incompatibility 

### ISSUE THREAD

**Issue by gustavoatt** [DataSystemsLab/GeoSpark#194]
While migrating to Spark 2.3 we weren't able to register Geospark SQL via

```
GeoSparkSQLRegistrator.registerAll
```

because of a potential change in `SparkSession.sessionState` API to register UDFs https://github.com/DataSystemsLab/GeoSpark/blob/dd55fea5ee260fd09bb9b945e8b8a0514044a193/sql/src/main/scala/org/datasyslab/geosparksql/UDF/UdfRegistrator.scala#L34

**Comment by jiayuasu** [comment]
@gustavoatt This has been fixed. To use GeoSparkSQL, read the new Maven Coordinate: [http://datasystemslab.github.io/GeoSpark/news/GeoSpark-All-Modules-Maven-Central-Coordinates/](http://datasystemslab.github.io/GeoSpark/news/GeoSpark-All-Modules-Maven-Central-Coordinates/)

**Comment by gustavoatt** [comment]
Thanks @jiayuasu for such a quick fix!
