### ISSUE TITLE
Support Different Spatial/Geometrical Data Format

### ISSUE THREAD

**Issue by Sarwat** [DataSystemsLab/GeoSpark#2]
GeoSpark need to support different input and output data format:

GML(Geography Markup Language)
WKT (Well-Known Text)
WKB (Well-Known Binary)

**Comment by sabman** [comment]
Add the very popular GeoJSON to the list

**Comment by sabman** [comment]
@Sarwat looks like geojson and wkt is supported see:
https://github.com/DataSystemsLab/GeoSpark/blob/master/src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java#L94
https://github.com/Sarwat/GeoSpark/blob/ed2f35d3d901950ad998309b51496ff8fb1bc64e/src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java#L98

**Comment by jiayuasu** [comment]
Thanks for your interests!

Yes. We now support GeoJSON and WKT as inputs. You can try them.

**Comment by lrojas94** [comment]
May I ask how to you support it? By this I mean, I have a CSV file which is in WKT... should I just change the format?

**Comment by lrojas94** [comment]
Also, note this line says wtk instead of wkt. 

https://github.com/DataSystemsLab/GeoSpark/blob/master/src/main/java/org/datasyslab/geospark/spatialRDD/PolygonRDD.java#L98

**Comment by jiayuasu** [comment]
Hi,

We support CSV, TSV, GeoJSON, and WKT. 

For CSV and TSV, you need to specify from which column (base is 0) the spatial coordinate data starts in case that the first several columns are IDs or other useless information. Then the reader will read coordinates from that column, for each row.

For GeoJSON and WKT, you can directly load data from the source file.

**Comment by jiayuasu** [comment]
That WTK is a typo and it will be fixed along with other new features in the next few weeks.

**Comment by sabman** [comment]
@jiayuasu see #7 for more typos

**Comment by jiayuasu** [comment]
@sabman Thanks for pointing this out. I will fix it later on.

**Comment by tiwanpunit** [comment]
Do you support shapefile also?

**Comment by jiayuasu** [comment]
Hi, currently, no. But we can add it in the future version. We now support reading/writing  csv, tsv, wkt and GeoJSON.

**Comment by jak2030** [comment]
It is not possible to initialize (for instance) a `PolygonRDD` with a `wkt`-formatted `String`? The various `spatialRDD` objects must be initialized by passing filepaths. Is that accurate? Thank you very much.

**Comment by rroyhere** [comment]
Hi, do you support shp files yet as input format?

**Comment by jiayuasu** [comment]
@rroyhere Sorry. We haven't finished the shape file input support. You probably can convert it to WKT or CSV and then use GeoSpark to load it.

**Comment by geoHeil** [comment]
Actually, using geotools in spark to perform such conversions in parallel fashion is pretty easy and opens a door to a variety of geo-formats.

**Comment by jiayuasu** [comment]
ESRI ShapeFile support is now available in GeoSpark 0.8.0.

**Comment by rroyhere** [comment]
This is awesome to know. Can't wait to try it out.

Thanks

**Comment by markgis** [comment]
Are there any plans to add other geospatial formats? Geopackage would be amazing!
