### ISSUE TITLE
Not sure of the order of arguments to be passed to new Envelope

### ISSUE THREAD

**Issue by sunilgc0** [DataSystemsLab/GeoSpark#20]
While creating a new envelope, is the order x1,x2,y1,y2 or is it different In the example provided, I saw the order was different as y1,y2,x1,x2 like -
val queryEnvelope=new Envelope (-113.79,-109.73,32.99,35.08);

**Comment by jiayuasu** [comment]
Hi,
This is not a GeoSpark issue.
