### ISSUE TITLE
org.apache.spark.sql.AnalysisException: Undefined function on yarn

### ISSUE THREAD

**Issue by alifiyaali** [DataSystemsLab/GeoSpark#208]
This exception occurs when code is deployed on yarn and the same code works fine when `master` is `local`. I am using these coordinates:

>artifactId : geospark-sql_2.1
>version : 1.1.1-SNAPSHOT

Exception which occurs for all GeoSpark functions:

>org.apache.spark.sql.AnalysisException: Undefined function: 'ST_Within'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; 

In some test cases I found that this exception occurs in `geospark-sql_2.1:1.0.1` as well. And `geospark-sql:1.0.1` works fine on cluster.

I am using `Java v1.8` and `Scala v2.11.8` on cluster.

**Comment by jiayuasu** [comment]
@alifiyaali In Spark 2.1, registering an expression based UserDefinedFunction is not combined with a spark session. This could be the reason. This issue/bug of Spark has been fixed by Spark 2.2 and 2.3.

To fix this issue in Spark 2.1 and GeoSpark, can you try to manually paste the following code in your program? (after the declaration of the SparkSession, keep GeoSparkSQLRegistrator.registerAll(sparkSession) as well):

```
FunctionRegistry.builtin.registerFunction("ST_PointFromText", ST_PointFromText)
FunctionRegistry.builtin.registerFunction("ST_PolygonFromText", ST_PolygonFromText)
FunctionRegistry.builtin.registerFunction("ST_LineStringFromText", ST_LineStringFromText)
FunctionRegistry.builtin.registerFunction("ST_GeomFromWKT", ST_GeomFromWKT)
FunctionRegistry.builtin.registerFunction("ST_GeomFromWKB", ST_GeomFromWKB)
FunctionRegistry.builtin.registerFunction("ST_GeomFromGeoJSON", ST_GeomFromGeoJSON)
FunctionRegistry.builtin.registerFunction("ST_Circle", ST_Circle)
FunctionRegistry.builtin.registerFunction("ST_Point", ST_Point)
FunctionRegistry.builtin.registerFunction("ST_PolygonFromEnvelope", ST_PolygonFromEnvelope)
FunctionRegistry.builtin.registerFunction("ST_Contains", ST_Contains)
FunctionRegistry.builtin.registerFunction("ST_Intersects", ST_Intersects)
FunctionRegistry.builtin.registerFunction("ST_Within", ST_Within)
FunctionRegistry.builtin.registerFunction("ST_Distance", ST_Distance)
FunctionRegistry.builtin.registerFunction("ST_ConvexHull", ST_ConvexHull)
FunctionRegistry.builtin.registerFunction("ST_Envelope", ST_Envelope)
FunctionRegistry.builtin.registerFunction("ST_Length", ST_Length)
FunctionRegistry.builtin.registerFunction("ST_Area", ST_Area)
FunctionRegistry.builtin.registerFunction("ST_Centroid", ST_Centroid)
FunctionRegistry.builtin.registerFunction("ST_Transform", ST_Transform)
FunctionRegistry.builtin.registerFunction("ST_Intersection", ST_Intersection)
sparkSession.udf.register("ST_Envelope_Aggr", new ST_Envelope_Aggr)
sparkSession.udf.register("ST_Union_Aggr", new ST_Union_Aggr)
```

**Comment by alifiyaali** [comment]
@jiayuasu I am unable to find the equivalent code in Java for the code you have mentioned. Can you help?

**Comment by jiayuasu** [comment]
@alifiyaali I am not able to find the code for Java as well...
