### ISSUE TITLE
Undefined function: 'ST_GeomFromWKT'

### ISSUE THREAD

**Issue by SrinivasRIL** [DataSystemsLab/GeoSpark#212]
Hi,

We are getting an error..
Undefined function: 'ST_GeomFromWKT' This function is neither a registered temporary function nor a permanent function registered in the database 'default'
We have imported all the packages (import org.apache.spark.sql.geosparksql.expressions
import org.datasyslab.geosparksql.UDF)  yet we are getting the same error .

The following is our scala code for creating a polygon dataframe from a wkt file stored in hdfs

`var sparkSession = SparkSession.builder()
.appName("readTestScala") // Change this to a proper name
.config("spark.serializer", classOf[KryoSerializer].getName)
.config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
.getOrCreate()

GeoSparkSQLRegistrator.registerAll(sparkSession.sqlContext)

var polydf = sparkSession.read.format("csv").option("delimiter", ",").option("header", "true").load("hdfs:///gis/COE6418/mumbaibldgwkt.csv")
polydf.createOrReplaceTempView("polydf")

var polygonDf = sparkSession.sql(
  """
    |SELECT ST_GeomFromWKT(polydf.SHAPE) AS shape
    |FROM polydf
  """.stripMargin)
polygonDf.createOrReplaceTempView("polygons")`

we are able to create a datframe, but when we try to use ST_GeomFromWKT or any other functions we are getting the same error as above. (in .printSchema() and .show() methods)

We also tried to register the udf's manually by
FunctionRegistry.builtin.registerFunction("ST_GeomFromWKT", ST_GeomFromWKT) but we get No Value found ST_GeomFromWKT

Kindly request you to help us 
## Settings

GeoSpark version = ?
1.1
Apache Spark version = ?
2.1
JRE version = 1.8?
1.8.0_151
API type = Scala or Java?
Scala

**Comment by jiayuasu** [comment]
@SrinivasRIL Can you try GeoSparkSQL template project? https://github.com/jiayuasu/GeoSparkTemplateProject

I just tested the sql template project with Spark version 2.1.2. It works fine.

**Comment by 1001010010** [comment]
Hi, How do you solve this problem?
