### ISSUE TITLE
Use Spatial Indexes in Geospark SQL?

### ISSUE THREAD

**Issue by paulzwu** [DataSystemsLab/GeoSpark#217]
## Expected behavior
I see Geospark provides Quad-Tree and R-Tree indexes.. Can we let SparkSQL choose which index?
## Settings

GeoSpark version = ?

Apache Spark version = ?

JRE version = 1.8?

API type = Scala or Java?

**Comment by jiayuasu** [comment]
@paulzwu Yes, you can do it. Please read [1] to set the spatial index used in GeoSparkSQL join query.

[1] Set GeoSparkSQL parameter: http://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Parameter/

**Comment by pedromorfeu** [comment]
I have the flag `geospark.global.index` set to `true` and still the distance query is taking too long:
```
val result = session.sql("SELECT * FROM tiles, pois WHERE ST_Distance(ST_GeomFromWKT(tiles.rddshape), ST_GeomFromWKT(pois.rddshape)) < 100")
``` 

The indexes work correctly (faster) in GeoSpark Core. Am I missing anything else?

**Comment by jiayuasu** [comment]
@pedromorfeu Please read some comments from this post:https://github.com/DataSystemsLab/GeoSpark/issues/218

**Comment by pedromorfeu** [comment]
Thanks. I've followed a couple the suggestions from #218, but still it takes much longer than GeoSpark Core.

This is what I have now:
```
.config("spark.serializer", classOf[KryoSerializer].getName)
.config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
.config("geospark.global.index", "true")
.config("geospark.global.indextype", "quadtree")
.config("geospark.join.gridtype", "kdbtree")
...
val result = session.sql("SELECT * FROM tiles t, pois p WHERE ST_Distance(t.rddshape, p.rddshape) < 100")
```

I also tried to set partitions (times 2-4) in the dataframes.
