### ISSUE TITLE
AkNN Queries

### ISSUE THREAD

**Issue by mklaber** [DataSystemsLab/GeoSpark#226]
I have a set of 1MM points. For each point, I want to find its 5 nearest neighbours. (The [All nearest neighbours](https://en.wikipedia.org/wiki/Nearest_neighbor_search#All_nearest_neighbors) problem.)

I can do this in traditional postgresql + PostGIS extensions:

```sql
SELECT *
FROM (
  SELECT 
          a.id, 
          b.id AS nth_id, 
          ST_Distance(a.geom, b.geom) AS distance, 
          ROW_NUMBER() OVER (PARTITION BY a.id ORDER BY ST_Distance(a.geom, b.geom)) AS nn_row
  FROM a, b
  WHERE a.id <> b.id
) c
WHERE c.nn_row <= 5
```

While I was able to get this query to work with Spatial SQL for a small set, it died on 10K records, which suggests I'm not building a scalable solution.

Question: is there a recommended approach? Is there an index that lends itself well to AkNN queries? Does Spatial SQL even add indexes itself? What about spatial joins?

**Comment by mklaber** [comment]
@jiayuasu is that your way of saying the query above is basically the best I'm going to be able to do using GeoSparkSQL?

**Comment by jiayuasu** [comment]
@mklaber The query you gave me doesn't seem to be a spatial query except you call "ST_Distance". So its performance depends on Spark itself.

Your query uses PARTITION BY, ORDER BY, and a self inequality join. This query is very slow for sure since the data can be huge.
