### ISSUE TITLE
SpatialKnnQuery with index fails

### ISSUE THREAD

**Issue by mklaber** [DataSystemsLab/GeoSpark#227]
## Expected behavior

The KNN Query with index example in the tutorial should work:
http://datasystemslab.github.io/GeoSpark/tutorial/rdd/#use-spatial-indexes_1

## Actual behavior

Exception:

```
java.lang.NoSuchMethodError: com.vividsolutions.jts.index.strtree.STRtree.kNearestNeighbour(Lcom/vividsolutions/jts/geom/Envelope;Ljava/lang/Object;Lcom/vividsolutions/jts/index/strtree/ItemDistance;I)[Ljava/lang/Object;
	at org.datasyslab.geospark.knnJudgement.KnnJudgementUsingIndex.call(KnnJudgementUsingIndex.java:80)
	at org.datasyslab.geospark.knnJudgement.KnnJudgementUsingIndex.call(KnnJudgementUsingIndex.java:44)
```

Likely because JTS's `STRtree` does not have a `kNearestNeighbour ` method.
GeoSpark's call: https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/knnJudgement/KnnJudgementUsingIndex.java#L80

Definition of STRtree: http://grepcode.com/file/repo1.maven.org/maven2/com.vividsolutions/jts/1.13/com/vividsolutions/jts/index/strtree/STRtree.java?av=f

## Steps to reproduce the problem

Just run the example from the tutorial.

## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.2.0.2.6.4.5-2

JRE version = 1.8

API type = Scala

Config:

`spark.jars.packages` &rarr; `org.datasyslab:geospark:1.1.3,org.datasyslab:geospark-sql_2.2:1.1.3,org.datasyslab:geospark-viz:1.1.3`

**Comment by jiayuasu** [comment]
@mklaber Matt, I know that. The KNN function in JTS official repo is written by me. However, GeoSpark uses a customized JTS library called JTSplus. JTSplus is packaged into GeoSpark already. Don't specify any other JTS in your project.  https://github.com/jiayuasu/JTSplus

**Comment by mklaber** [comment]
@jiayuasu I'm not specifying any other JTS in my project. Only `spark.jars.packages` → `org.datasyslab:geospark:1.1.3,org.datasyslab:geospark-sql_2.2:1.1.3,org.datasyslab:geospark-viz:1.1.3`

**Comment by jiayuasu** [comment]
@mklaber Hi, if you use GeoSpark RDD API. JTSplus should work fine. Did you try GeoSpark template project? https://github.com/jiayuasu/GeoSparkTemplateProject
