### ISSUE TITLE
Df.count takes forever 

### ISSUE THREAD

**Issue by AlexTo** [DataSystemsLab/GeoSpark#228]
## Expected behavior

Df.count should finish quickly

## Actual behavior

Df.count takes forever

## Steps to reproduce the problem

Load the shape data in the link below. The zip file contains 4 files: LGA_2016_AUST.dbf, LGA_2016_AUST.prj, LGA_2016_AUST.shp, LGA_2016_AUST.shx

The exact code is in the screenshot. In my setup, LGA folder on HDFS is the folder containing 4 files listed above.

Call count() on the data frame => takes forever. I used ogr2ogr tool to load the same shape files into PostGis, it has only 536 records.

[LGA shape files](https://drive.google.com/open?id=1deZ8OL1jCpbXci7fVkHpmpheu0ZZJIT_)

## Settings

GeoSpark version = 1.1.2

Apache Spark version = 2.3.0

JRE version = 1.8.162

API type = Scala

![screen shot 2018-05-02 at 10 24 45 am](https://user-images.githubusercontent.com/296212/39499865-fe961ed0-4df3-11e8-9c38-570d690f3345.png)

**Comment by jiayuasu** [comment]
@AlexTo Verified. This is a potential bug. Not sure about the reason. Will fix it in 1.2.0. For now, use any tools to convert this shapefile to WKT TSV file. It can be loaded by GeoSparkSQL perfectly.

**Comment by jiayuasu** [comment]
@zongsizhang Please handle this.

**Comment by zongsizhang** [comment]
@jiayuasu I'm working on this
