### ISSUE TITLE
JavaNullPointerException while reading  polygon WKT 

### ISSUE THREAD

**Issue by SrinivasRIL** [DataSystemsLab/GeoSpark#229]
Hi @jiayuasu 

In the previous thread , you had suggested to use wkt instead of geojson.
We changed the input format to wkt.
We are able to create dataframes for the points and the polygons from their respective wkt files.
We are basically trying to find which points lie within the polygon and we tried many scenarios (permutatons of no of fields in polygon  and the count of polygons)
The polygon wkt file has 60 odd fields and 3 lakh records. 

1) We performed ST_Intersection on points with the above polygon and we got the error as follows

> org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 48.0 failed 4 times, most recent failure: Lost task 0.3 in stage 48.0 (TID 101, bdppocdatanode13.jio.com, executor 1): java.lang.NullPointerException

2) We performed the same query and reduced the fields , and we were able to get the desired result.  

3) We then reduced the number of records but kept all fields and we were able to get the desired results for  around 50K polygon records, but when we exceeded that limit, we got the same error.

Just to be on the safer side, we also tried removing blankspaces and replaced them with **'none'**, but no change in results.

So I am not sure what is the cause of this issue.  The query is as follows
`var ContainsDF = sparkSession.sql("select ST_Intersection(spatialDf.polyshape,pointspdf.pointshape) as shape, spatialDf.building_rjid as building_rjid,pointspdf.ADDRESS as address from spatialDf, pointspdf where ST_Intersects(spatialDf.polyshape,pointspdf.pointshape) ")`

Appreciate your help @jiayuasu 
Thanks

## Settings

GeoSpark version = 1.1.2

Apache Spark version = 2.1

JRE version = 1.8

API type = Scala

**Comment by jiayuasu** [comment]
@SrinivasRIL Do you mind to post the full stack trace, especially the part of "caused by"? I cannot learn the error information from what you posted which is just general Spark error information.

**Comment by SrinivasRIL** [comment]
Hi @jiayuasu 
I am pretty sure the geometry fields are not null, else I wouldnt have been able to create a dataframe??
I am able to display the records in polygon and points  dataframe, and I am also taking only uniqueid column  and the shape column which are not null.  Else while performing df.show() it should have given me the error. But after the intersection operation we are getting this error.
We have a few other columns that have null records, that we replaced to **none**. 
Also, we are able to perform the same query  successfully with all the records but fewer fields (including the geometry fields)

**Comment by jiayuasu** [comment]
@SrinivasRIL Note that: df.show() only partially materializes a data table. This means, if you run df.show(20), Spark will only generate the first 20 rows. df.show will not find the errors.

To verify the original file is error-free and can pass `ST_GeomFromWKT`, use some commands can trigger a full data frame materialization such as `df.write.save("/my/path/myfile")`
