### ISSUE TITLE
jar pushed to maven : too fat ?

### ISSUE THREAD

**Issue by mdespriee** [DataSystemsLab/GeoSpark#23]
Hi folks,
Thank you for adding geospark to maven repo. 
I think you may have a problem with the jar you build and push to maven, though. 
Your jar includes way too much classes from dependencies (one can found scala std lib classes, py4j classes, etc.). This may lead to classpath conflict, or may be the cause of issue 22 for instance.
Mathieu

**Comment by jiayuasu** [comment]
Hi,

Thanks for your interest!

I think this is caused by Issue 22.

The GeoSpark in Maven central is compiled with Spark 2.0.0.

I think this can be easily solved by changing GeoSpark Pom file. If you want, you can put GeoSpark source code in your local project, change the Pom and compile together.

Thanks,
Jia

**Comment by jiayuasu** [comment]
Hi,

I updated GeoSpark in Maven Central to support Spark 2.0.1. Please refer to this link: https://github.com/DataSystemsLab/GeoSpark/issues/22.

Please let me know if you still meet difficulties.

When compiling GeoSpark, I only include Apache Spark dependency but Spark itself contains many dependencies such as Scala and Py4j.

**Comment by mdespriee** [comment]
Thanks for the update with spark2.0.1. We will test right away.

Let me talk again about dependency : I think your jar in maven repo should not include classes from spark, py4j or scala. These are "provided dependencies". 
I suggest you have a look to any other lib relying on spark (say this one that I just picked for the example : https://mvnrepository.com/artifact/com.xpatterns/spark-job-rest-api/0.3.0), you'll see that spark is a provided dep, and any of spark class is included in the final jar.

My 2 ct.
We are very interested in your lib, by the way.

**Comment by jiayuasu** [comment]
Hi Mathieu,

Thanks for your suggestion. It is helpful! I have reduced the jar and re-published GeoSpark to Maven Central.

Thanks,
Jia
