### ISSUE TITLE
the Pixel's method equals throws NullPointException

### ISSUE THREAD

**Issue by konvish** [DataSystemsLab/GeoSpark#231]
## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.2.1

JRE version = 1.8

API type = Java

I use PointRDD to plot HeatMap,but when this.distributedRasterCountMatrix reduceByKey,it will throw NullPointException.
![image](https://user-images.githubusercontent.com/19517952/39903080-f607a2ea-5503-11e8-916a-3f451ed8683c.png)
So I try to write a filter ahead,But it still NullPointException.I foreach to print data,and it has no null data.
and I find the NullPointException is from the Pixel of method equals. why the parameter will be null.
I make the class extends Pixel and override method equals.It will be work success.
![image](https://user-images.githubusercontent.com/19517952/39903335-4cebb9ba-5505-11e8-969b-2cab120ca0f3.png)
![image](https://user-images.githubusercontent.com/19517952/39903344-594a6d64-5505-11e8-9d01-c06d01e5d500.png)
![image](https://user-images.githubusercontent.com/19517952/39903377-7e7d205e-5505-11e8-9146-6a70fe7f4f0c.png)

**Comment by jiayuasu** [comment]
@konvish Thanks for finding this! This issue was first found by Issue #164 . But I was not able to reproduce it. Now I know how to reproduce it. I will fix it in 1.2.0.
