### ISSUE TITLE
Slow "INNER JOIN" with ST_CONTAINS

### ISSUE THREAD

**Issue by AlexTo** [DataSystemsLab/GeoSpark#239]
GeoSpark version = 1.1.3

Apache Spark version = 2.3

JRE version = 1.8

API type = Scala

I have a simple join statement as follows:

```
SELECT df1.*, df2.* FROM df1 
 INNER JOIN df2 
 ON 1=1 WHERE ST_CONTAINS(df1.WKB_GEOMETRY, df2.WKB_GEOMETRY) = TRUE
```

Basically, what I want to do is that I only want the rows from both df1 and df2 where df2.WKB_GEOMETRY is completely contained by df1.WKB_GEOMETRY

I tried to run the above query in PostGIS and GeoSpark (on the same server) and they seem to produce similar results but GeoSpark takes significantly longer (like almost 2 days) where PostGIS takes about 1 hour. 

I am using local[*] so all my 48 cores are max at 100%, the server has 512GB Ram, about 256GB is used by the Spark job. I also initialized sparkSession like this

```
val spark: SparkSession = SparkSession
  .builder()
  .config("spark.serializer", classOf[KryoSerializer].getName)
  .config("spark.kryo.registrator", classOf[GeoSparkKryoRegistrator].getName)
  .appName("bitre")
  .getOrCreate()
```

Any suggestions about what I can do to speed it up?

**Comment by jiayuasu** [comment]
Thanks @AlexTo 

Discussion details can be found in this thread: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/geospark-discussion-board/-4Jnr9v2Vfo/Rox9B7l1AgAJ

This is not a bug. Will capture this pattern in 1.2.0.

**Comment by jiayuasu** [comment]
@zongsizhang Please handle this.

**Comment by jiayuasu** [comment]
@AlexTo The correct syntax should be

```
SELECT df1.*, df2.* FROM df1 
 INNER JOIN df2 
 ON ST_CONTAINS(df1.WKB_GEOMETRY, df2.WKB_GEOMETRY)
```

This will trigger geospark join
