### ISSUE TITLE
New Method setGrid

### ISSUE THREAD

**Issue by Tsarazin** [DataSystemsLab/GeoSpark#24]
Hi guys, 
I want to create a PointRDD and a PolygonRDD from a rdd of Point and a rdd of Polygon. I am using the method 
    /**
     * Initialize one SpatialRDD with one existing SpatialRDD
     * @param rawPointRDD One existing rawPointRDD
     */
    public PointRDD(JavaRDD<Point> rawPointRDD) {
        this.setRawPointRDD(rawPointRDD);
    }

But when I do this the grids of my PointRDD and PolygonRDD are not created and I can't make a match between my PointRDD and Polygon. If i didn't misunderstand the grid is only created if you create your PointRDD from a csv file. Can you make a new method that set the grid too from a rdd? That's would be very useful for me.

**Comment by jiayuasu** [comment]
Hi,

There is a bypass. Since I make all attributes in PointRDD and PolygonRDD as "public", you can access them directly like this "pointRDD1.grids = pointRDD2.grids;"

Let's say there is a PointRDD is initialized and the sample code should be like this:

val pointRDD1 = new PointRDD(sc, "/home/SparkUser/arealm.csv", 0 ,"csv","rtree",4);

val pointRDD2 = new PointRDD(pointRDD1.getRawPointRDD());

pointRDD2.grids = pointRDD1.grids;

pointRDD2. gridPointRDD = pointRDD1.gridPointRDD;

Thanks,
Jia

**Comment by Tsarazin** [comment]
Hi, 
Yes sure but the problem here is that i don't have pointRDD1, I get a JavaRDD of Point that I obtained after some calculs, the data are not stored in a file in my computer. I am creating a PointRDD with the method val rdd_point = new PointRDD(JavaRDD<Point>); but the grids and the gridPointRDD are not created and so I can't do spatial queries. For the moment I copy your code from the constructor val pointRDD1 = new PointRDD(sc, "/home/SparkUser/arealm.csv", 0 ,"csv","rtree",4); to create a grid and a gridPointRDD and then do like you said
val grids = (...)
val gridPointRDD = (...)

pointRDD2.grids = grids;
pointRDD2. gridPointRDD = gridPointRDD
 but it will be easier for me if you create a method like 
 public PointRDD(JavaSparkContext sc, JavaRDD<Point> rawPointRDD, String gridType, Integer numPartitions)

**Comment by jiayuasu** [comment]
OK. Got your point. I totally agree with it. We need to add this function into GeoSpark as soon as possible. For now, the grid pointRDD is only used in Spatial Join Query so that you can use the Range and KNN without having grid PointRDD.

Thank you very much for your suggestion!

**Comment by Tsarazin** [comment]
Thanks for your consideration. Let me know when it's done.

**Comment by jiayuasu** [comment]
Hi @Tsarazin ,

I have solved this problem by adding a new Spatial RDD constructor in GeoSpark 0.3.2.

Thanks,
Jia

**Comment by Tsarazin** [comment]
Hi @jiayuasu , 
Yes I saw that's perfect thanks a lot!
