### ISSUE TITLE
The X of the point of the Geospark stands for longitude or latitude

### ISSUE THREAD

**Issue by FlyoverBlind** [DataSystemsLab/GeoSpark#240]
## Settings

GeoSpark version = ?

Apache Spark version = ?

JRE version = 1.8?

API type = Scala or Java?

**Comment by devlucasc** [comment]
Hi @FlyoverBlind, X is for longitude and Y is for latitude.
Imagine a chart.... Your vertical axis is a Y, and your horizontal axis is a X. The same with lat/lon.

**Comment by FlyoverBlind** [comment]
Thanks @devlucasc , but when I run this sparksql
select ST_Transform(ST_GeomFromWKT('Point(100.027 33.46)'),'EPSG:4326','EPSG:3857')  from a
throws org.geotools.referencing.operation.projection.ProjectionException: latitude 100.027 is too close to a pole.

**Comment by jiayuasu** [comment]
Hi @FlyoverBlind ,

Please read this: http://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Function/#st_transform

```
By default, ST_Transform assumes Longitude/Latitude is your coordinate X/Y. If this is not the case, set UseLongitudeLatitudeOrder as "false".
```

Probably, you can try 

```
SELECT ST_Transform(polygondf.countyshape, 'epsg:4326','epsg:3857',false, false)
FROM polygondf
```
