### ISSUE TITLE
Drop the support of Circle geometry in SQL interface

### ISSUE THREAD

**Issue by jiayuasu** [DataSystemsLab/GeoSpark#245]
## Actual behavior
Circle object is not a standard type in common geospatial data format. In GeoSpark, it is mainly used to help distance join. The radius of the circles serve as the buffer.

This actually leads to lots of confusion when GeoSpark users want to convert it back to the normal geometry. Will use ST_Buffer or ST_DWithin to solve this issue in the next release.

## Settings

GeoSpark version = All till 1.1.3

Apache Spark version = all

JRE version = all

API type = SQL in Scala and Java

**Comment by pedromorfeu** [comment]
@jiayuasu, is it safe, tough, to use `Circle`, `CirceRDD` and `ST_Circle` in `1.1.3`?
For instance, I'm noticing that, in a join query circle/point, points that fall in the boundary of a circle aren't considered to be intersecting/contained.

**Comment by jiayuasu** [comment]
ST_Circle shouldn't be used in 1.1.3. This may lead to wrong results.

CircleRDD in RDD API should be only used for distance join.

In order to do a distance join in SQL API, use this instead
http://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Optimizer/#distance-join

------------------------------------

Jia Yu,

Ph.D. Student in Computer Science

Arizona State University <http://www.asu.edu/>

Reach me via Jia Yu's Homepage <http://www.public.asu.edu/~jiayu2/> | GitHub
Repositories <https://github.com/jiayuasu>

**Comment by pedromorfeu** [comment]
Thanks @jiayuasu. Your example is in GeoSpark SQL, but I guess I can also use GeoSpark Core's equivalent: 
```
JoinQuery.DistanceJoinQueryFlat(objectRddB, circleRDD, usingIndex, considerBoundaryIntersection)
```
So I can have better control over indexes/partitioning.

**Comment by pedromorfeu** [comment]
@jiayuasu, looks like distance join isn't considering points that fall in boundary of the circle. However, in PostGIS does consider them.
Example:
```
select ST_within(
	cast(ST_SetSRID(ST_GeomFromText('POINT (1.0436518037 41.6345011605)')::geography,4326) as geometry), 
	cast(st_buffer(ST_SetSRID(ST_GeomFromText('POINT (1.04125843698 41.6345227856)')::geography,4326), 200::float) as geometry)
)
```
