### ISSUE TITLE
JoinQuery

### ISSUE THREAD

**Issue by Tsarazin** [DataSystemsLab/GeoSpark#25]
Hi guys, 
I would like to make a join between two dataframes which contain geospatial data. One of them has a column which contains Points and the other one has a columns which contains Polygons. I want to make a join between theses two dataframes using these two columns. The problem is that i can transform the columns in PointRDD and PolygonRDD and then make the query but it will only return to me a rdd containing Polygon and a list of Point. It is not what I am looking for, I am looking for the index. 
Imagine I got
df1 = ((Row_Id,Point),(1,P1),(2,P2),(3,P3),(4,P4))
df1 = ((Row_Id,Polygon),(1,Po1),(2,Po2),(3,Po3),(4,Po4),(5,Po5))
I want
1  5
2  3
2  4
with P1 is in Po5, P2 is in Po3 and Po4.

The best would be if I can do like a join in spark 
 val matchedRowsDF = rfqDF.joinWith(rfsDF, rfqDF(m.rfqColName) === rfsDF(m.rfsColName))
but using your algorithm.

Thanks for any advices.

**Comment by jiayuasu** [comment]
Hi @Tsarazin ,

JTSplus objects now can carry original input data. Besides the spatial objects itself, GeoSpark will load input data tuple into JTSplus spatial object UserData attribute. Once you get the Join result, you can use point.getUserData() to retrieve the input.

This also works for all Point, Envelope, and Polygon objects in GeoSpark.

Please let me know if you have questions.

Thanks,
Jia

**Comment by jiayuasu** [comment]
Hi @Tsarazin ,

GeoSpark now goes to 0.3.2. The latest GeoSpark jar has been synced to all Maven central.

Thanks,
Jia
