### ISSUE TITLE
"Node capacity must be greater than 1"

### ISSUE THREAD

**Issue by Tsarazin** [DataSystemsLab/GeoSpark#28]
I noticed when you want to create a PointRDD with a rtree grid from a rdd with 100 units 
new PointRDD(rddPoint,"rtree",1)
you get an error "Node capacity must be greater than 1"
totalNumberOfRecords = 100
sampleNumberOfRecords =totalNumberOfRecords/100 = 1
nodecapacity = sampleNumberOfRecords / NumPartitions = 1
I think it will be better if the user can choose the percentage of data used to create the grid (new parameter) or if totalNumberOfRecords/100 = 1 sampleNumberOfRecords is equal to 0 (like it is the case if totalNumberOfRecords/100 < 1).
I know you don't really need a rtree for a dataset with 100 rows, it just that I don't want that my system crash if there is a shitty dataset in my workspace.
thanks for your consideration.

**Comment by jiayuasu** [comment]
Soloved in GeoSpark 0.4.0
