### ISSUE TITLE
JoinQuery.SpatialJoinQuery throw a Exception

### ISSUE THREAD

**Issue by meSuperMario** [DataSystemsLab/GeoSpark#285]
## Expected behavior
use SpatialRDD to query
## Actual behavior
throw a NoClassDefFoundError Exception
## Settings

GeoSpark version = 1.1.3

Apache Spark version = 1.6

JRE version = 1.8

API type = Java

**Comment by jiayuasu** [comment]
For Spark 1.X, you should use GeoSpark 0.8.2, http://datasystemslab.github.io/GeoSpark/download/GeoSpark-All-Modules-Maven-Central-Coordinates/#apache-spark-1x-versions

**Comment by meSuperMario** [comment]
> For Spark 1.X, you should use GeoSpark 0.8.2, http://datasystemslab.github.io/GeoSpark/download/GeoSpark-All-Modules-Maven-Central-Coordinates/#apache-spark-1x-versions

thanks for your help, I already resolve this problem.
