### ISSUE TITLE
com.vividsolutions.jts.geom.TopologyException on SpatialJoinQueryFlat

### ISSUE THREAD

**Issue by m4nzh** [DataSystemsLab/GeoSpark#287]
## Expected behavior
I want to decrease geometry (polygon) points float decision or apply convexHull on geometry and expected to have a success join

## Actual behavior
TopologyException with description "side location conflict" regardless of decreasing decision / convexHull transformation

## Steps to reproduce the problem
1. I make a dataframe of WKT and then creating a SpatialRDD from DataFrame. 
2. Do CRSTransformation to translate geometry from EPSG:3576 to EPSG:4326 (I tried to remove it, but error still occures)
3. Trying to decrease decision of points in geometry and do a join
4. Building indexes and do spatialPartitioning on both RDD in join
5. Joining

3. Code looks like that:
```
def convexHullGeometry(spatialRDD: SpatialRDD[Geometry]): SpatialRDD[Geometry] = {
    val newSpatialRDD = new SpatialRDD[Geometry] // i'have also tried modify rawSpatialRdd on existing spatialRDD without creating a new one

    val rdd = spatialRDD.rawSpatialRDD.rdd
      .map(geom => {
        val userData = geom.getUserData
        val scale = Math.pow(10, 4) // i want to only 4 digits after comma in double
        val newGeom = GeometryPrecisionReducer.reduce(geom, new PrecisionModel(scale))
        // val newGeom = geom.convexHull // another way of rescuing TopologyException
        println(geom.toText)
        println(newGeom.toText)
        newGeom.setUserData(userData)
        newGeom
      })

    newSpatialRDD.rawSpatialRDD = rdd
    newSpatialRDD
  }
```

So without this transformation code error looks like:
com.vividsolutions.jts.geom.TopologyException: side location conflict [ (55.30554100092851, 52.03084499997882, NaN) ]
When I try to do decreasing decision transformation I got error like this:
com.vividsolutions.jts.geom.TopologyException: side location conflict [ (55.30554100092851, 52.03084499997882, NaN) ]

Why points still have the same double decision? I expected not to see error or to see something like:
[ (55.3055, 52.0308, NaN) ] if I downgrade decision. 
## Settings

GeoSpark version = 1.1.3

Apache Spark version = 2.2.0

JRE version = 1.8

API type = Scala
****

**Comment by jiayuasu** [comment]
@m4nzh Please use ST_PrecisionReduce in GeoSpark 1.2.0-SNAPSHOT
http://datasystemslab.github.io/GeoSpark/api/sql/GeoSparkSQL-Function/#st_precisionreduce

Snapshot coordinate: http://datasystemslab.github.io/GeoSpark/download/GeoSpark-All-Modules-Maven-Central-Coordinates/#snapshot-versions
