### ISSUE TITLE
ST_IsValid Failed to process all geometries if there are one Invalid Geometry

### ISSUE THREAD

**Issue by netanel246** [DataSystemsLab/GeoSpark#291]
## Expected behavior
Write invalid geometry to log, and continue processing the valid geometries
## Actual behavior
Throws invalid Geometry exception and not proceeding to the next geometries
## Steps to reproduce the problem
Using this code, we can read invalid geometry a, and then a valid geometry, b.
I would expect to write to log the invalid geometry and continue processing the valid one,
and not get an exception because of the invalid geometry a.
```
var testtable=sparkSession.sql(
        "SELECT ST_IsValid(ST_GeomFromWKT('POLYGON((0 0, 10 0, 0 0))')) AS a, " +
        "ST_IsValid(ST_GeomFromWKT('POLYGON ((30 10, 40 40, 20 40, 10 20, 30 10))')) as b"
      )
```

## Settings

GeoSpark version = 1.1.3, 1.2.0

Apache Spark version = 2.3.0

JRE version = 1.8

API type = Scala With Java

**Comment by jiayuasu** [comment]
@netanel246 I don't think this is an issue. ST_GeomFromWKT should throw exceptions for wrong geometries which don't satisfy the meaning of a polygon (e.g., only 2 points, or, wrong WKT syntax). ST_Invalid is to find the geometries that are "topology invalid" but in correct geometries syntax.

The users should make sure all input WKT strings are correct in terms of grammar.

Please read PostGIS explanation: https://postgis.net/docs/ST_IsValid.html

**Comment by netanel246** [comment]
OK. Thanks for your replay.
I have a problem that when I am using Generic Spatial RDD with some of the
geometries are invalid, I got an exception and the process terminate. I
expected that if there are some invalid geometries, they will be written to
log, and the process will continue to work on the valid ones.

I have dirty data, which can contain invalid geometries, and I always fail
on those invalid geometries and therefore can't process that data.

I found that I can handle this if I will add try...catch block to swallow
the exception and write to log the error, and returning null instead of
geometry.
Do you think it's a valid bug?

**Comment by netanel246** [comment]
OK. But how can I handle Generic SpatialRDD which contains a mix of valid and invalid geometries?
In the current version, I got an exception, and I expected to process the other valid geometries, and basically swallow the invalid geometries and write the error to log.

**Comment by jiayuasu** [comment]
For RDD and SQL, I would suggest that write your own filter function (in SparkSQL, it should an UDF). In this filter, try to read geometry string like this: https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/main/scala/org/apache/spark/sql/geosparksql/expressions/Constructors.scala#L134

If catch an exception, return false, otherwise return true

**Comment by netanel246** [comment]
Thanks. Can I do it also with GeoJson? because I don't see in the Constructors.scala file that you mentioned a function for reading a GeoJson...

**Comment by netanel246** [comment]
Also, when I tested it with some invalid GeoJsons, and I think I can't handle it with a UDF. Because my code keep falling on this row:
https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/formatMapper/FormatMapper.java#L156

I saw that in the validation of the JTS the invalid geometries failed, and the all process terminate.
In order to fix that, I need to wrap the readGeoJson function in the [FormatMapper](https://github.com/DataSystemsLab/GeoSpark/blob/master/core/src/main/java/org/datasyslab/geospark/formatMapper/FormatMapper.java#L151)
with a `Try...Catch` phase.
I think this will help other folks who need to deal with invalid geometries..
What do you think about it?
