### ISSUE TITLE
Can't parse multiline geojson using ST_GeomFromGeoJSON

### ISSUE THREAD

**Issue by adatisjose** [DataSystemsLab/GeoSpark#294]
I am trying to read a GeoJSON file in Azure Databricks similar to the following:

{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
}

The Scala code I'm using is:

var polygonJsonDf = sparkSession.read.format("com.databricks.spark.csv").option("delimiter","\t").option("header","false").load("/mnt/geospatial/POLYGONS.geojson")

polygonJsonDf.createOrReplaceTempView("polygontable")
polygonJsonDf.show(false)

The result of this DataFrame is:
+--------------------------------+
|_c0                             |
+--------------------------------+
|{                               |
|  "type": "Feature",            |
|  "geometry": {                 |
|    "type": "Point",            |
|    "coordinates": [125.6, 10.1]|
|  },                            |
|  "properties": {               |
|    "name": "Dinagat Islands"   |
|  }                             |
|}                               |
+--------------------------------+

The issue happens when I'm trying to read the Dataframe using ST_GeomFromGeoJSON.
var polygonDf = sparkSession.sql(
        """
          | SELECT ST_GeomFromGeoJSON(polygontable._c0) AS countyshape
          | FROM polygontable
        """)
polygonDf.show()

org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 31.0 failed 4 times, most recent failure: Lost task 0.3 in stage 31.0 (TID 43, 10.139.64.6, executor 1): java.lang.RuntimeException: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: {; line: 1, column: 0])

I understand the problem is because the json row is in multiple lines, so my question is: how can I read a multi line geojson file using GeoSparkSQL?

## Settings

GeoSpark version = 1.1.3
GeoSparkSQL version = 2.3 1.1.3

Apache Spark version = 2.3.1

API type = Scala 2.11

**Comment by netanel246** [comment]
You cannot. what you can do is to transform the geoJson file into a row json.
