### ISSUE TITLE
Add option to skip invalid geometries in result RDD of GeoJsonReader.readToGeometryRDD

### ISSUE THREAD

**Issue by AntonPeniaziev** [DataSystemsLab/GeoSpark#297]
## Expected behavior
When creating a spatial rdd from geoJson file, there should
an option to pass a flag invalidGeomsEnabled with default value True.
## Actual behavior
An rdd will always conatin invalid geometries if there are some invalid geometries in geoJson file
## Steps to reproduce the problem
Create an rdd from geoJson file with some invalid geometry. There will be crash on any attempt to evaluate 
## Settings

GeoSpark version = 1.2.0

Apache Spark version =  2.3.0

JRE version = 1.8

API type = Scala and Java

**Comment by jiayuasu** [comment]
@AntonPeniaziev This is good. Please go ahead and implement it. 

If the user wants to make the GeoJSON reader silent, we will do try-catch. If we catch an exception when loading a record in GeoJSON RDD, we should skip this geometry instead of printing null geometry.
