### ISSUE TITLE
Provide an API option to skip/fix geometries with invalid syntax

### ISSUE THREAD

**Issue by AntonPeniaziev** [DataSystemsLab/GeoSpark#299]
## Expected behavior
There are multiple GIS tools as ArcMap that can produce geometries with invalid syntax, like
POLYGON( (0 0, 1 0, 0 0) ) - Invalid number of points in LinearRing (found 3 - must be 0 or >= 4)
POLYGON( (0 0, 1 0, 1 1, 0 1) ) - Points of LinearRing do not form a closed linestring
Those geometries could be a part of big files 10M lines+

Objective: provide an option for user to skip known exceptions only. Provide user an option to implement a "fixer" interface and supply a fixing class object that will make the geometry valid (for example, to close a linestring - add the first point as last)
## Actual behavior 
Crash with exceptions specified above
## Steps to reproduce the problem
Make geometries from provided WKTs
## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.3.0

JRE version = 1.8

API type = Java

**Comment by avshRepo** [comment]
+1

**Comment by jiayuasu** [comment]
@AntonPeniaziev This is good. Please go ahead and implement it.

If the user wants to make the GeoJSON reader silent, we will do try-catch. If we catch an exception when loading a record in GeoJSON RDD, we should skip this geometry instead of printing null geometry.
