### ISSUE TITLE
Support LineStringRDD

### ISSUE THREAD

**Issue by Sarwat** [DataSystemsLab/GeoSpark#3]
A LineString is a one-dimensional object representing a sequence of points and the line segments connecting them.

**Comment by TBuc** [comment]
Hi, I'm interested in this feature. Any news about its development progress?
Thank you.

**Comment by jiayuasu** [comment]
Hi Antonio,

Thanks for your interests in GeoSpark!

We are working on the next version of GeoSpark which will contain LineStringRDD. It will be released in one month.

Cheers,
Jia

**Comment by TBuc** [comment]
Hi Jia,

good to know! Can't wait for it.
Thank you all for your work.

Antonio

**Comment by dsdinter** [comment]
Hi,
I see this feature is still not available after more than a year from last comment.
Do you have any timelines about this?
We are benchmarking some Geospatial engines and one of our datasets include Linestring so we are really interested to have this feature to be able to benchmark Geospark.
Is there anyway we can help, i.e., testing PR?

Regards.

**Comment by jiayuasu** [comment]
Hi @dsdinter ,

Thanks for reminding us! We will add native support of LineStringRDD and associated Spatial Partitioning, Range, KNN and Join in GeoSpark 0.4. This update will happen by middle December.

Regards,
Jia

**Comment by jiayuasu** [comment]
Soloved in GeoSpark 0.4.0
