### ISSUE TITLE
Getting Exception in thread "main" java.lang.NoClassDefFoundError: org/datasyslab/geosparksql/utils/GeoSparkSQLRegistrator$

### ISSUE THREAD

**Issue by beovolytics** [DataSystemsLab/GeoSpark#324]
## Settings

GeoSpark version = ?

Apache Spark version = ?

JRE version = 1.8?

API type = Scala or Java?

**Comment by beovolytics** [comment]
Please Find Below Version which i am using in my currently Project



GeoSpark version = 1.1.3

Apache Spark version = 2.3.0

JRE version = 1.8

API type = Scala

**Comment by jiayuasu** [comment]
Please make sure you correctly setup GeoSpark Maven dependencies. http://datasystemslab.github.io/GeoSpark/tutorial/sql/#set-up-dependencies

**Comment by ps-spark** [comment]
Hi @jiayuasu,

I have a similar problem with the new release 1.2. I have implemented a reverse geocoding program using the SpatialKNNQuery based on the _snapshots_ artefacts. It worked fine. Today, I replaced the artefacts to _maven central_ 1.2 and wanted to run the code.

- sbt update: runs fine
- sbt clean/compile: no problem
- no errors in Intellij, no red lines
- SparkSession has been created such as in the Tutorial

If I run the code with `GeoSparkSQLRegistrator.registerAll(spark)` I got the following error (however I don't use GeoSparkSQL in my code):

`xception in thread "main" java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/Geometry
	at org.apache.spark.sql.geosparksql.UDT.UdtRegistratorWrapper$.registerAll(UdtRegistratorWrapper.scala:25)
	at org.datasyslab.geosparksql.UDT.UdtRegistrator$.registerAll(UdtRegistrator.scala:24)
	at org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator$.registerAll(GeoSparkSQLRegistrator.scala:33)`

If I run without it:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/datasyslab/geospark/serde/GeoSparkKryoRegistrator
	at org.datasyslab.geosparkviz.core.Serde.GeoSparkVizKryoRegistrator.registerClasses(GeoSparkVizKryoRegistrator.java:34)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:135)
	at org.apache.spark.serializer.KryoSerializer$$anonfun$newKryo$6.apply(KryoSerializer.scala:135)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)`

When I open the `org.datasyslab.geospark.jar`, Intellij shows a red line under `GeoSparkKryoRegistrator` and doesn't find the class. Of course he is also there in the jar.

What am I doing wrong? Any hint would be appreciated.

Best wishes,
ps-spark

**Comment by jiayuasu** [comment]
@ps-spark This is very strange. I don't know what's going on. Probably because of wrong Maven cache? 

Can you try to directly run one of the template projects in your Intellij?
https://github.com/jiayuasu/GeoSparkTemplateProject

**Comment by ps-spark** [comment]
I deleted the whole ivy cache and downloaded all artifacts again. Same problem.

![2019-03-12_16h09_05](https://user-images.githubusercontent.com/19947879/54211313-625b6d00-44e1-11e9-8430-b0402b00ad62.png)

Could be the problem that I use Scala version 2.11.8 and GeoSpark was built with 2.1?

**Comment by ps-spark** [comment]
Hi @jiayuasu,

I set the repository back to **`1.2.0-SNAPSHOT`** and voila, it works again. At least if I don't use `GeoSparkSQLRegistrator.registerAll(spark)`. If I use it I got the following error:

`Exception in thread "main" java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.analysis.FunctionRegistry.createOrReplaceTempFunction(Ljava/lang/String;Lscala/Function1;)V
	at org.datasyslab.geosparksql.UDF.UdfRegistrator$$anonfun$registerAll$1.apply(UdfRegistrator.scala:38)
	at org.datasyslab.geosparksql.UDF.UdfRegistrator$$anonfun$registerAll$1.apply(UdfRegistrator.scala:38)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.datasyslab.geosparksql.UDF.UdfRegistrator$.registerAll(UdfRegistrator.scala:38)
	at org.datasyslab.geosparksql.utils.GeoSparkSQLRegistrator$.registerAll(GeoSparkSQLRegistrator.scala:43)`

So, there is definitely a bug in the maven artifact: **`"org.datasyslab" % "geospark" % "1.2.0" % "provided"`**

Could you please check it, if you have time?

Thank you and best wishes,
ps-spark

**Comment by jiayuasu** [comment]
@ps-spark 

If you use "provided" when packaging the jar, this is definitely wrong. All GeoSpark package should be in "compile" scope otherwise these packages won't be included.

In addition, make sure your GeoSpark SQL version is corresponding the correct Spark version.

GeoSparkSQL-1.2.0_2.3 means it supports Spark 2.3+(including 2.4)

**Comment by ps-spark** [comment]
Hallo @jiayuasu,

Thank you very much for the quick response. Indeed, if I use the following artifacts it works:

`  lazy val geoSparkDependencies = Seq(
    "org.datasyslab" % "geospark" % "1.2.0",
    "org.datasyslab" % "geospark-sql_2.1" % "1.2.0",
    "org.datasyslab" % "geospark-viz_2.1" % "1.2.0"
  )`

Could you please update the documentation as well? 
[http://datasystemslab.github.io/GeoSpark/download/GeoSpark-All-Modules-Maven-Central-Coordinates/](url) It still shows the 1.1.3 artifacts.

![2019-03-13_14h02_31](https://user-images.githubusercontent.com/19947879/54281133-5af79a80-4599-11e9-9812-a576b4d50e6d.png)

Best wishes,
ps-spark

**Comment by jiayuasu** [comment]
@ps-spark Thanks for letting me know! I just fixed it.
