### ISSUE TITLE
ST_Union_Aggr ClassCastException

### ISSUE THREAD

**Issue by jonrein** [DataSystemsLab/GeoSpark#328]
## Expected behavior

I'm trying to do a union of polygons that were formed using ST_GeomFromText

## Actual behavior

First lines of stacktrace:

19/02/14 13:04:35 WARN TaskSetManager: Lost task 125.0 in stage 31.0 (TID 2804, datanode13, executor 1): java.lang.ClassCastException: com.vividsolutions.jts.geom.MultiPolygon cannot be cast to com.vividsolutions.jts.geom.Polygon
        at org.apache.spark.sql.geosparksql.expressions.ST_Union_Aggr.update(AggregateFunctions.scala:61)

## Steps to reproduce the problem

Everything runs fine with a sample dataset run locally, so I'm unfortunately unable to replicate the problem in a way that would provide a tractable test case.

## Settings

GeoSpark version = 1.2.0-SNAPSHOT

Apache Spark version = 2.3.0

JRE version = 1.8

API type = Scala

**Comment by jiayuasu** [comment]
@jonrein Does your data contain "MultiPolygon" type? Are you sure all your polygons can be unioned to a single polygon instead of a set of polygons?

**Comment by jonrein** [comment]
@jiayuasu The individual row elements are all Polygons, but they don't union to a single closed polygon.  Running ST_Union on the full column locally returns a MultiPolygon without problems.  Maybe it's a serialization/deserialization thing?

**Comment by jonrein** [comment]
SOLVED: When I switched from using GeoSpark 1.1.3 to 1.2.0, sbt assembly was still using the cached v1.1.3 classes.  So my local runs were using 1.2.0, and the fat jar that I shipped out to the cluster was using 1.1.3.  Clearing the cache and reassembling with sbt worked.
