### ISSUE TITLE
Add native support of Spark DataFrame and Spark SQL

### ISSUE THREAD

**Issue by jiayuasu** [DataSystemsLab/GeoSpark#33]
Currently, GeoSpark manipulates the original Spark RDD. Some users suggest that adding the native support of Spark DataFrame may help people. We will add the native support in the upcoming versions. 

For now, an easy workaround to get DataFrame rdd is that:
1. To get a spatial partitioned DataFrame, call GeoSpark myPointRDD. gridPointRDD / myRectangelRD.gridRectangelRDD / myPolygonRDD.gridPolygonRDD to get the spatial partitioned Spark RDD and then convert it to DataFrame.
2. To get a DataFrame from Range query result or any Spatial RDDs , call myPointRDD.getRawPointRDD() / myRectangelRDD.getRawRectangelRDD() / myPolygonRDD.getRawPolygonRDD() and then convert it to DataFrame.

**Comment by geoHeil** [comment]
Are the names still the same? myPointRDD. gridPointRDD does not seem to be available, but a raw java RDD.
By the way if I am using scala is it a problem if a java RDD is used?

**Comment by jiayuasu** [comment]
Hi, GeoSpark internal code has been reorganized since this post. You should call spatialPartitionedRDD and rawSpatialRDD instead.

**Comment by geoHeil** [comment]
So basically the following should work if sql context with its implicits is loaded.

```
objectRDD.rawSpatialRDD.toDF().show
objectRDD.rawSpatialRDD.rdd.toDS().show
```
but will fail to find the toDF/ toDS methods for this type of RDD.

**Comment by jiayuasu** [comment]
OK. I will look into that.

**Comment by geoHeil** [comment]
Are there any plans to implement a good Kryo Encoder http://stackoverflow.com/questions/36648128/how-to-store-custom-objects-in-a-dataset because otherwise `joinResult.rdd.toDF.show` will fail with Missing Encoder error.
