### ISSUE TITLE
No ST_GeomFromGeoJSON function in 1.2.0-snapshot for spark 2.3

### ISSUE THREAD

**Issue by Wrussia** [DataSystemsLab/GeoSpark#333]
## Expected behavior
ST_GeomFromGeoJSON(<geojson string>) give a valid result

## Actual behavior
```
GeoSparkSQLRegistrator.registerAll(spark)

spark.read
  .option("delimiter", "\t")
  .csv("./udf/src/test/resources/a.json")
  .createOrReplaceTempView("a")

spark.sql("select ST_GeomFromGeoJSON(_c0) from a").show
```

> Undefined function: 'ST_GeomFromGeoJSON'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 7
org.apache.spark.sql.AnalysisException: Undefined function: 'ST_GeomFromGeoJSON'. This function is neither a registered temporary function nor a permanent function registered in the database 'default'.; line 1 pos 7

## Settings

GeoSpark version = 1.2.0-SNAPSHOT

Apache Spark version = 2.3

JRE version = 1.8

API type = Scala

**Comment by Wrussia** [comment]
I see, that appeared `readToGeometryRDD` method, but what I should do, if I have GeoJson column?

**Comment by jiayuasu** [comment]
@Wrussia 
If you have a GeoJSON file, how can it become a GeoJSON column?

In 1.2.0, the correct way to read a GeoJSON file to a DataFrame is here

https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/test/scala/org/datasyslab/geosparksql/constructorTestScala.scala#L80

All other attributes will also be carried together.

**Comment by Wrussia** [comment]
I have csv file with column in GeoJSON format like 
```
col1 \t {"type":"Feature","geometry":{"type":"MultiPolygon","coordinates":[<coord list>]},"properties":{<prop list>}} \t col3 \t col4
```
That's strange, I know, but I have to work with such data.(

**Comment by jiayuasu** [comment]
All right. I got your point. In that case, using ST_GeomFromGeoJSON in GeoSpark 1.1.3 will be your only choice. I will try to recover this SQL function in 1.2.0 but not sure whether it will confuse people.

**Comment by Wrussia** [comment]
I've made pull request 
https://github.com/DataSystemsLab/GeoSpark/pull/335
