### ISSUE TITLE
Performance of Range Query

### ISSUE THREAD

**Issue by tiwanpunit** [DataSystemsLab/GeoSpark#34]
For testing performance of GeoSpark, I created a polygon of 7 points(got coordinates from google maps). I am reading those points from KML file and converted Polygon to JavaRDD<Polygon>. Then I indexed PolygonRDD using "rtree".
To find out whether a particular **point** is inside given **polygon** or not I am using **RangeQuery**.
On my local machine, its taking 32ms(approx) to give me result. My Polygon won't change for lifetime so I cached JavaRDD<Polygon> but still it took approx 32ms when I ran it several times.
So when I run RangeQuery, does spark build the tree at that particular time and then try to find whether given envelope is in range of that polygon or range query itself is taking this much time?
Note: I have only one polygon in my PolygonRDD

**Comment by jiayuasu** [comment]
Hi @tiwanpunit ,

Thanks for asking this interesting question. In fact, we have done some research on this.

First, I am not sure whether you are using the proper format to do iterative range query. Here is the proper format to do iterative range query with cache. (The query envelope can be replaced by JTS Polygon)

```
    	PointRDD objectRDD = new PointRDD(sc, inputLocation, offset, splitter);
    	objectRDD.rawPointRDD.persist(StorageLevel.MEMORY_ONLY());
    	for(int i=0;i<loopTimes;i++)
    	{
    		long resultSize = RangeQuery.SpatialRangeQuery(objectRDD, queryEnvelope, 0).getRawRectangleRDD().count();
    		assert resultSize>-1;
    	}
```

```
PointRDD objectRDD = new PointRDD(sc, inputLocation, offset, splitter);
    	objectRDD.buildIndex("rtree");
    	for(int i=0;i<loopTimes;i++)
    	{
    		long resultSize = RangeQuery.SpatialRangeQueryUsingIndex(objectRDD, queryEnvelope, 0).getRawRectangleRDD().count();
    		assert resultSize>-1;
    	}
```

Second, I have tested GeoSpark range query with cache on super large data. The benefit of using spatial index in range query is not very obvious, it takes some additional time to build index in the first round execution. 

Moreover, range query is actual "Map" operation. This is called Narrow Dependency in Spark and a bunch of same range queries can be pipelined together and executed without a stop. The pipeline execution is super fast and using index is just a little bit faster than it. You may not even notice it.

Thanks,
Jia

**Comment by tiwanpunit** [comment]
Thank you for replying so fast.
So in my usecase "objectRDD" is the "point" and "queryEnvelope" is the "polygon" ? i.e. objectRDD contains the points that need's to be queried and queryEnvelope is the shape on which query is performed.
Did I understand your explanation correctly?

Also you have suggested to pass JTS Polygon in place of "queryEnvelope" but the method only accepts "Envelope" type of shape not Polygon.

**Comment by jiayuasu** [comment]
1. Yes. You understand me correctly.
2. Yes. You are right. Thanks for reminding me. Currently, it only supports Envelope type as the query window. I can add the support of polygon type query window in the upcoming version. It is very easy.

For now, it seems the only way to perform a polygon window range query is  to do a join query on PolygonRDD(only 1 polygon inside) and PointRDD.

**Comment by jiayuasu** [comment]
Soloved in GeoSpark 0.4.0
