### ISSUE TITLE
ST_Buffer results in an oval - Spark -1.2.0 ST_Circle - Dropped

### ISSUE THREAD

**Issue by BottleSpink** [DataSystemsLab/GeoSpark#341]
This is a doubt rather than an issue. Why was ST_Circle dropped and I understand ST_Buffer is to be used in place of ST_Circle. But when I use ST_Buffer, polygon results in an oval shape. What if I have a requirement for a circular boundary? 

![Capture](https://user-images.githubusercontent.com/18397758/54208434-ec1b3280-4501-11e9-8b21-c8610640d460.PNG)

GeoSpark version = 1.2.0

Apache Spark version = 2.1

JRE version = 1.8?

API type = Scala

**Comment by jiayuasu** [comment]
@BottleSpink I think oval is the correct map visualization result because of coordinate projection. Please read this link: https://github.com/Turfjs/turf/issues/110

**Comment by BottleSpink** [comment]
Thank You!
