### ISSUE TITLE
GeoJsonReader incorrectly handles "id"

### ISSUE THREAD

**Issue by sergiimk** [DataSystemsLab/GeoSpark#344]
## Expected behavior

When loading GeoJSON that contains the optional "id" the "id" column should be added to the resulting RDD along with key-value data in feature "properties".

## Actual behavior

When loading following GeoJSON:
```json
{"type":"Feature","id":0,"properties":{"zipcode":"00101","name":"A"},"geometry":{"type":"Polygon","coordinates":[[[0.0,0.0],[10.0,0.0],[10.0,10.0],[0.0,10.0],[0.0,0.0]]]}}
{"type":"Feature","id":1,"properties":{"zipcode":"00202","name":"B"},"geometry":{"type":"Polygon","coordinates":[[[0.0,0.0],[20.0,0.0],[20.0,20.0],[0.0,20.0],[0.0,0.0]]]}}
```
as
```scala
val rdd = GeoJsonReader.readToGeometryRDD(spark.sparkContext, filePath, false, false)
val df = Adapter.toDf(rdd, spark)
df.show(false)
```
the resulting DataFrame looks like this:
```
+---------------------------------------+-------+-----+
|geometry                               |zipcode|name |
+---------------------------------------+-------+-----+
|POLYGON ((0 0, 10 0, 10 10, 0 10, 0 0))|0      |00101|
|POLYGON ((0 0, 20 0, 20 20, 0 20, 0 0))|1      |00202|
+---------------------------------------+-------+-----+
```

Notice that "zipcode" column actually contains the "id", while "name" values are missing.

When "id" is not present the data frame looks as expected.

## Steps to reproduce the problem

Load above GeoJSON file

## Settings
GeoSpark version = 1.2.0
Apache Spark version = 2.4.0
JRE version = 1.8
API type = Scala

**Comment by jiayuasu** [comment]
@mikhtonyuk I will look into this. Thanks for reminding us!
