### ISSUE TITLE
Distance between point is not clear

### ISSUE THREAD

**Issue by AlexStanovsky** [DataSystemsLab/GeoSpark#357]
Related to : https://github.com/DataSystemsLab/GeoSpark/issues/260

I am executing the the following distance computation:

    spark.sql("select  ST_DISTANCE(ST_TRANSFORM(ST_POINT(2.3476409912109375, 48.85884228699205),'epsg:4326','epsg:3857'),ST_TRANSFORM(ST_POINT(2.3510313034057617,48.864742993190475 ),'epsg:4326','epsg:3857') )").show(false)

Distance in meters between 2 points after conversion from `epsg:4326` to `epsg:3857`
1. lng -  2.3476409912109375, lat - 48.85884228699205 (Paris)
2. lng - 2.3510313034057617, lat - 48.864742993190475 (Paris)

The real distance is approximated to `705m` and the query result is `1067.406m`

What am I missing here ?

**Comment by AlexStanovsky** [comment]
I found the issue, I didn't use the right coord system.
It should be [`epsg:27572`](https://epsg.io/?q=France&page=5) instead of `epsg:3857`

**Comment by AlexStanovsky** [comment]
Is there a way to get the UTM projection from given lng/lat?

**Comment by jiayuasu** [comment]
@AlexStanovsky It is not possible to infer a projection system from a given lng/lat.
