### ISSUE TITLE
package does not exist

### ISSUE THREAD

**Issue by AntreasPetsas** [DataSystemsLab/GeoSpark#381]
I am currently trying to learn geospark for educational purpose.
I install Intellij a java IDE, i download geospark and then i import it to IDE.
Intellij auto download and import necessary libraries and dependencies.
Then i press Build Module "geospark-parent"(no errors, or warnings)

After all thinks have been installed, I select one of the two example geospark provides. I choose Example.java and run it. (core\src\main\java\org\datasyslab\geospark\showcase)

## Actual behavior
19 Errors after compiling and 5 warnings.
Look below for errors.

## Settings

GeoSpark version = 1.2.0

Apache Spark version = ?

JRE version = 1.8.0_202 ( Adopt Open JDK )

API type = Scala or Java?? I am not sure.( I think scala )

## Errors on class JoinQuery
Error: java: package org.datasyslab.geospark.monitoring does not exist

Error: java: cannot find symbol
  symbol:   class GeoSparkMetric
  location: class org.datasyslab.geospark.spatialOperator.JoinQuery

## Errors on class DynamicIndexLookupJudgement
Error: java: package org.datasyslab.geospark.monitoring does not exist

Error: java: cannot find symbol
  symbol:   class GeoSparkMetric
  location: class org.datasyslab.geospark.joinJudgement.DynamicIndexLookupJudgement<T,U>

##Warnings
Warnings are about classes than have been deprecated.

![problem1](https://user-images.githubusercontent.com/17071207/62643322-62f11600-b950-11e9-9f0d-ae0fc5494e1f.png)
![problem2](https://user-images.githubusercontent.com/17071207/62643324-62f11600-b950-11e9-9f86-b3a64a311943.png)

**Comment by jiayuasu** [comment]
@AntreasPetsas Please don't use the showcase class if you don't want to change GeoSpark source code. Please use GeoSparkTemplateProject instead: https://datasystemslab.github.io/GeoSpark/tutorial/GeoSpark-Runnable-DEMO/

**Comment by AntreasPetsas** [comment]
I try one of the Template(Example.java) and i am still getting the error i mention above.

**Comment by uniysfu** [comment]
@AntreasPetsas I got the same problem with you( java cannot find class geospark.monitoring.GeoSparkMetric). And I also need to change the source code, but first the problems above are not solved.

**Comment by AntreasPetsas** [comment]
@uniysfu i resolved the problem. I give some instructions in your issue. If you have any concerns, let me know. I'm clossing this issue.

**Comment by uniysfu** [comment]
@AntreasPetsas thanks mate, I solved the problem as well. The key thing for me is to switch to jdk1.8 and that's all. thank you for your instruction mate.

**Comment by uniysfu** [comment]
@AntreasPetsas hi friend, I am using windows and need add HADOOP_HOME in your system variables.
How do I know the path of Hadoop? The Hadoop is used as a maven dependency.

**Comment by AntreasPetsas** [comment]
The path of Hadoop in my windows computer is : C:\Users\antreas\.m2\repository\org\apache\hadoop\hadoop-common\2.7.2\bin

before add this path, check if you have the folder bin, because in my pc was missing.
If find the folder online here(  https://stackoverflow.com/questions/19620642/failed-to-locate-the-winutils-binary-in-the-hadoop-binary-path ).
Just download it and add it to your hadoop-common\2.7.2 folder. Then add HADOOP_HOME.

Sorry for the late reply!
