### ISSUE TITLE
Poor performance of dataframe count

### ISSUE THREAD

**Issue by larrywong98** [DataSystemsLab/GeoSpark#382]
Counting 39000000 polygons takes about 190s-240s, while pyspark takes only 10s-12s and spark for 5s instead. Here is my result using geospark.

scala> inst_boxes.show(5, false)
+-----------------------------------------------------------------------------------------------------+
|shape                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------+
|POLYGON ((496.413 844.32, 496.413 844.56, 497.325 844.56, 497.325 844.32, 496.413 844.32))|
|POLYGON ((1274.75 978, 1274.75 978.24, 1275.03 978.24, 1275.03 978, 1274.75 978))              |
|POLYGON ((686.223 633.84, 686.223 634.08, 686.451 634.08, 686.451 633.84, 686.223 633.84))|
|POLYGON ((241.053 878.88, 241.053 879.12, 241.566 879.12, 241.566 878.88, 241.053 878.88))|
|POLYGON ((261.972 878.88, 261.972 879.12, 262.371 879.12, 262.371 878.88, 261.972 878.88))|
+-----------------------------------------------------------------------------------------------------+
only showing top 5 rows
scala>         inst_boxes.createOrReplaceTempView("inst_blks")
scala>         val resultDf = spark.sql(
     |         """
     |         select * from inst_blks
     |         where ST_Intersects(
     |                   ST_PolygonFromEnvelope(cast(100.0 as Decimal(24,10)),
     |                                          cast(100.0 as Decimal(24,10)),
     |                                          cast(800.0 as Decimal(24,10)),
     |                                          cast(500.0 as Decimal(24,10))), shape)
     |         """
     |         )
scala> val st = System.currentTimeMillis
st: Long = 1565320436532

scala> val count = resultDf.count
count: Long = 39542887

scala> val et = System.currentTimeMillis
et: Long = 1565320758629

scala> println("Count: " + count + ", time consumed: " + (et-st)/1000.0 + " second")
Count: 39542887, time consumed: 322.097 second

**Comment by jiayuasu** [comment]
@larrywong98 The reason is simply because you don't have enough partition for this DataFrame so the spatial join inside runs in a sub-optimal fashion. Try to double or triple your current num of partitions in that dataframe.

It is worth noting that, GeoSpark DataFrame is not as good as GeoSpark RDD API.

We have provided a way for you to easily use GeoSpark RDD API inside your SparkSQL program. Please check this example: https://github.com/DataSystemsLab/GeoSpark/blob/master/sql/src/test/scala/org/datasyslab/geosparksql/adapterTestScala.scala#L136

**Comment by larrywong98** [comment]
Thanks! that definitely help me solve the problem.
