### ISSUE TITLE
How do geospark process data?

### ISSUE THREAD

**Issue by larrywong98** [DataSystemsLab/GeoSpark#389]
When using ST_Contains(Point,Shape), data is proceeded in memory or remote?

**Comment by larrywong98** [comment]
If proceeded in remote, could you refer your code to me. Thanks!

**Comment by jiayuasu** [comment]
@larrywong98 Sorry, I didn't get it. What do you mean data is in memory or remote? The workload is distributed to the entire cluster

**Comment by larrywong98** [comment]
So the workload is evenly distributed to the cluster?

**Comment by larrywong98** [comment]
@jiayuasu So the workload is evenly distributed to the cluster?

**Comment by larrywong98** [comment]
@jiayuasu So the workload is evenly distributed to the cluster? Distributed to each machine's memory in the cluster?

**Comment by jiayuasu** [comment]
Yes, you are right

**Comment by larrywong98** [comment]
Thanks!
