### ISSUE TITLE
how to join spatialrdd with a shapefile using RangeQuery.SpatialRangeQuery

### ISSUE THREAD

**Issue by kaushikCanada** [DataSystemsLab/GeoSpark#397]
## Expected behavior
var queryResult = RangeQuery.SpatialRangeQuery(spatialRDD, **rangeQueryWindow**, considerBoundaryIntersection, usingIndex)
rangeQueryWindow - how to make this a shapefile. should this only be an envelope?

## Settings

GeoSpark version = 1.2.0

Apache Spark version = 2.4

JRE version = 1.8?

API type = Scala or Java?

**Comment by netanel246** [comment]
According to the [documentation](https://datasystemslab.github.io/GeoSpark/tutorial/rdd/#range-query-window) it can be Point, Polygon or LineString.
You can read a shapefile that contains 1 geometry and use it as a rangeQueryWindow.

**Comment by kaushikCanada** [comment]
this can be done. experiments going on.
