### ISSUE TITLE
shapely.geometry.point.Point is not an instance of type GeometryType

### ISSUE THREAD

**Issue by brenotx** [DataSystemsLab/GeoSpark#436]
## Expected behavior
Following http://geospark.datasyslab.org/ 
Spatial SQL in Python > Creating Spark DataFrame based on shapely objects.

The example in Docs doesn't work.

## Actual behavior
```ValueError: field geom: <shapely.geometry.point.Point object at 0x112e82510> is not an instance of type GeometryType```

## Steps to reproduce the problem

```python
from pyspark.sql.types import IntegerType, StructField, StructType

from geospark.sql.types import GeometryType

schema = StructType(
    [
        StructField("id", IntegerType(), False),
        StructField("geom", GeometryType(), False)
    ]
)
```
Code expected to work:
```python
from shapely.geometry import Point

data = [
    [1, Point(21.0, 52.0)],
    [1, Point(23.0, 42.0)],
    [1, Point(26.0, 32.0)]
]


gdf = spark.createDataFrame(
    data,
    schema
)

gdf.show()
```
## Settings

GeoSpark version = 1.3.1

Apache Spark version = 3.0.0

API type = Python

**Comment by Imbruced** [comment]
Hi, 
The code which you used works for Spark 2.2, 2.3 and 2.4. I am not sure what about 3.0. After closing this PR #428 I can start working on giving support for Spark 3.0 preview.

**Comment by brenotx** [comment]
I forgot to mention but I tested using 2.4 Spark version and it is not working. I end up changing my Spark JDPC connection _stringtype_ option to _unspecified_ and sending points as WKT strings. Doing that, my database cast the value to _geometry_ type.

**Comment by Imbruced** [comment]
That is strange because I used your code with Spark 2.4 and it works. And you example is one of 400 test cases. https://github.com/DataSystemsLab/GeoSpark/blob/master/python/tests/serialization/test_serializers.py. Did you use `GeoSparkRegistrator.registerAll(spark)` ?
