### ISSUE TITLE
PySpark - Spatial KNN Query - JavaPackage object not callable

### ISSUE THREAD

**Issue by jornfranke** [DataSystemsLab/GeoSpark#444]
## Expected behavior
KNN nearest neighbors returns the k-nearest neighbors (using the corresponding functionality: https://datasystemslab.github.io/GeoSpark/tutorial/geospark-core-python/#write-a-spatial-knn-query)
```
from geospark.core.spatialOperator import KNNQuery
from shapely.geometry import Point

point = Point(-84.01, 34.01)
k = 10 ## K Nearest Neighbors
using_index = False
result = KNNQuery.SpatialKnnQuery(object_rdd, point, k, using_index)
````
Note: If I use Spark SQL with the ST_Distance function then it works perfectly fine. The spatial RDD is analysed before (without error) and works.

## Actual behavior
Exception is thrown:

```
TypeError: 'JavaPackage' object is not callable

TypeError                                 Traceback (most recent call last)
in engine
----> 1 result = KNNQuery.SpatialKnnQuery(spatial_rdd, point, k, using_index)

/home/cdsw/.local/lib/python3.6/site-packages/geospark/utils/decorators.py in run_function(*args, **kwargs)
     33
     34             if first_not_fulfill_value == -1:
---> 35                 return func(*args, **kwargs)
     36             else:
     37                 raise ModuleNotFoundError(f"Did not found {has_all_libs[first_not_fulfill_value]}, make sure that was correctly imported via py4j"

/home/cdsw/.local/lib/python3.6/site-packages/geospark/core/spatialOperator/knn_query.py in SpatialKnnQuery(self, spatialRDD, originalQueryPoint, k, useIndex)
     24         """
     25         jvm = spatialRDD._jvm
---> 26         jvm_geom = GeometryAdapter.create_jvm_geometry_from_base_geometry(jvm, originalQueryPoint)
     27
     28         knn_neighbours = jvm.KNNQuery.SpatialKnnQuery(spatialRDD._srdd, jvm_geom, k, useIndex)

/home/cdsw/.local/lib/python3.6/site-packages/geospark/utils/geometry_adapter.py in create_jvm_geometry_from_base_geometry(cls, jvm, geom)
     18         else:
     19             decoded_geom = GeometryFactory.to_bytes(geom)
---> 20             jvm_geom = jvm.GeometryAdapter.deserializeToGeometry(decoded_geom)
     21
     22         return jvm_geom

TypeError: 'JavaPackage' object is not callable
```

## Steps to reproduce the problem
I followed basically the tutorial on https://datasystemslab.github.io/GeoSpark/tutorial/geospark-core-python/#write-a-spatial-knn-query 

Note: If I implement the same functionality in SparkSQL with the ST_Distance function then it works perfectly fine. I assume thus the Geospark integration works quite well (Thank you for this great library btw.).

## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.0

JRE version = 1.8

API type = Python

**Comment by Imbruced** [comment]
Hi,
Did you use all 3 jar files ? 

**geo_wrapper_2.11-0.3.0.jar**
geospark-1.3.0.jar
geospark-sql_2.3-1.3.0.jar

It looks like bolded one is not available in your spark session. In next release I merged code from geo_wrapper_2.11-0.3.0.jar (now is available on master, on PyPI should be release with new version).

Regards,
Paweł

**Comment by jornfranke** [comment]
Oha Geo_wrapper might have been missing in the uberjar- thy I will try tomorrow

**Comment by jornfranke** [comment]
What are the maven coordinates for geo_wrapper?

**Comment by Imbruced** [comment]
That jar is available only as separate file https://pypi.org/project/geospark/#files after unzipping python package. (geospark/jars/). In next GeoSpark release the code can be found in GeoSpark core package (already available on master branch).

**Comment by jornfranke** [comment]
That works, thank you a lot.
