### ISSUE TITLE
Python API does not support spatialPartitioning(GridType gridType, int numPartitions)

### ISSUE THREAD

**Issue by gaodq** [DataSystemsLab/GeoSpark#447]
## Expected behavior
Why `public void spatialPartitioning(GridType gridType, int numPartitions)` not supported in Python API?

## Actual behavior
I found there is no numPartitions parameter in Python API `def spatialPartitioning(self, partitioning: Union[str, GridType, SpatialPartitioner, List[Envelope], JvmPartitioner]) -> bool:`
Is there any plan to support this interface?

## Steps to reproduce the problem
```
from geospark.core.formatMapper.shapefileParser import ShapefileReader
from geospark.core.enums import GridType
from geospark.core.enums import IndexType

shape_file_location = 'path_to_shapefile'

shape_rdd = ShapefileReader.readToGeometryRDD(sc, shape_file_location)
buildOnSpatialPartitionedRDD = True # Set to TRUE only if run join query
numPartitions = 50
shape_rdd.analyze()
shape_rdd.spatialPartitioning(GridType.RTREE, numPartitions) # <-- error
shape_rdd.buildIndex(IndexType.RTREE, buildOnSpatialPartitionedRDD)
```

## Settings

GeoSpark version = 1.3.1

Apache Spark version = 2.4.5

JRE version = 1.8.0_251

API type = Python

**Comment by Imbruced** [comment]
Hi, I forget to implement this. I add those changes, waiting for successful  build and after that I will create PR.

**Comment by gaodq** [comment]
Good job!
