### ISSUE TITLE
Simply Registering doesn't work!

### ISSUE THREAD

**Issue by maboualidev** [DataSystemsLab/GeoSpark#462]
## Expected behavior
No Error
## Actual behavior
Error
## Steps to reproduce the problem
>>> from pyspark.sql import SparkSession
>>> from geospark.register import upload_jars
>>> from geospark.register import GeoSparkRegistrator
>>> upload_jars()
True
>>> spark = SparkSession.builder.getOrCreate()
>>> GeoSparkRegistrator.registerAll(spark)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-1b84a908723b> in <module>()
----> 1 GeoSparkRegistrator.registerAll(spark)

~/.conda/envs/py368nb/lib/python3.6/site-packages/geospark/register/geo_registrator.py in registerAll(cls, spark)
     24         spark.sql("SELECT 1 as geom").count()
     25         PackageImporter.import_jvm_lib(spark._jvm)
---> 26         cls.register(spark)
     27         return True
     28 

~/.conda/envs/py368nb/lib/python3.6/site-packages/geospark/register/geo_registrator.py in register(cls, spark)
     29     @classmethod
     30     def register(cls, spark: SparkSession):
---> 31         return spark._jvm.GeoSparkSQLRegistrator.registerAll(spark._jsparkSession)
     32 
     33 

TypeError: 'JavaPackage' object is not callable
## Settings

GeoSpark version = ?
 1.3.1
Apache Spark version = ?
2
JRE version = 1.8?
1.8
API type = Scala or Java?
Python

**Comment by Imbruced** [comment]
The exception means that spark does not see all essential jar files. Can you check if they are visible on Spark Web UI ?

**Comment by maboualidev** [comment]
Yes, That was it. Typo in the address to include jar files.
