### ISSUE TITLE
Support insert into the RectangleRDD and the R-tree index

### ISSUE THREAD

**Issue by tharpa** [DataSystemsLab/GeoSpark#5]
It seems that the current implementation doesn't allow to insert new elements (envelopes) into the RectangleRDD and into the built R-tree index.  Unfortunately, I have a use case which requires just that as the envelopes are consumed from a dynamic stream of data coming into Spark using Spark streaming from a Kafka topic.

**Comment by jiayuasu** [comment]
Issue 148 about GeoSpark Streaming seems to be an answer for this (https://github.com/DataSystemsLab/GeoSpark/issues/148).
