### ISSUE TITLE
How to provide semantics on data?

### ISSUE THREAD

**Issue by invadergir** [DataSystemsLab/GeoSpark#53]
For the most part (except for one bug I found) I'm able to do spatial queries and calculate nearest neighbors, but I am unable to determine how to add semantics to the location data.  In other words, if each point is named, how can we get the names when doing a query?  For an example of what I mean, say we have a CSV with points that represent locations A, B, and C:

```
    A,0.0,0.0
    B,1.0,0.0
    C,2.0,0.0
```

When one does a KNN query, let's say the library returns the point (1.0, 0.0).  How are we to associate the point returned with the location name A, B, or C?  A lookup against an RDD or Dataframe on the same location dataset would be possible, but you would have to select the row using a key of the double values (X, Y).  This is probably okay, but doing that seems fragile.  For example, if the KNN query ever returned a calculated value for some reason rather than the actual bitwise representation stored in the dataset.  Also this assumes the dataset / spark / whatever uses the same bitwise representation.

Are we expected to do the lookup using the coordinates?  Or is there another method I'm not aware of?

Thanks...

**Comment by jiayuasu** [comment]
Hi @invadergir ,

GeoSpark JTS spatial object can carry the original input data when doing queries if you set the last parameter to "true"

```
val objectRDD = new PointRDD(sc, "/Users/jiayu/VM_Share/resources/arealm.csv", 0, FileDataSplitter.CSV, true);
```

After each query, you can just iterate each object and retrieve the original input row by calling

```
myPoint.getUserData()
```

Thanks,
Jia

**Comment by invadergir** [comment]
Thanks.. I'll try that.

**Comment by invadergir** [comment]
It looks like that getUserData() function returns a string, which is a copy of the line in the CSV file.

It's not great, but it should be usable.  I'll just have to parse it again.

Thanks...
