### ISSUE TITLE
LineStringRDD Constructor refer's to the wrong geometric type for raw JavaRDD

### ISSUE THREAD

**Issue by aldayj-intific** [DataSystemsLab/GeoSpark#60]
Raw constructor expects JavaRDD\<Polygon\>.
It should be expecting JavaRDD\<LineString\>

**Comment by jiayuasu** [comment]
Solved. See PR https://github.com/DataSystemsLab/GeoSpark/pull/61

**Comment by jiayuasu** [comment]
Maven central GeoSpark 0.5.2-snapshot has been updated.

**Comment by aldayj-intific** [comment]
Awesome. Thank you for the quick update on this.
