### ISSUE TITLE
custom input format

### ISSUE THREAD

**Issue by georgThesis** [DataSystemsLab/GeoSpark#66]
I have some ascii text files which contain meta data

```
    key value
    some other
    x 123
    y 456
```

and matrix of values (heatmap)

```
    0 1 4 5
    2 0 3 0
    0 2 3 0
    3 4 4 0
```

X and y specify bottom left corner of the object in WSG64 coordinate system, the matrix bottom left value starts there as well and is evenly spaced in a grid of lets say 10 meters.

Currently `gdal` and `ogr2ogr` are used to create a more readable csv
`filename_metadataKey_value`
which contains a `MULTIPOLYGON` of the matrix.

How could I use your custom input format to map the matrix to a multi polygon?

**Comment by jiayuasu** [comment]
Multiline input format in Hadoop/Spark requires a customized Hadoop file reader. GeoSpark will support some famous input formats such as Multiline GeoJSON and Shapefile. I am working on it.

**Comment by jiayuasu** [comment]
@georgThesis Multipolygon WKT object has been supported by GeoSpark native mapper. You can try it out.
