### ISSUE TITLE
cannot save image on hdfs

### ISSUE THREAD

**Issue by bertolinux** [DataSystemsLab/GeoSpark#68]
Hi all!
Compliments for excellent geospark and babylon libraries. 
I have problems saving image file to HDFS: when using local mode, no problems, when launching it as cluster mode, the save doesn't give errors but I cannot find files.
I tried using many format (hdfs://, etc...).
Could you provide me a very simple example to export images to HDFS, please?
I'm using 0.5.1 forma spark 2
Thank you
Best
Roberto

**Comment by jiayuasu** [comment]
@bertolinux Hi Roberto, could you tell me which generator you are using? NativeJavaGenerator or SparkGenerator?
