### ISSUE TITLE
Babylon unit test failure wrong path

### ISSUE THREAD

**Issue by geoHeil** [DataSystemsLab/GeoSpark#79]
Babylon unit test fail, as the path to 
`Caused by: java.io.IOException: Mkdirs failed to create file:/Users/jiayu/GitHub/GeoSpark-jiayu-repo/target/scatterplot/PointRDD-parallel-raster/_temporary/0/_temporary/attempt_20170423172254_0047_m_000003_280
`
is hard coded.

**Comment by jiayuasu** [comment]
This issue has been fixed.
