### ISSUE TITLE
Jts shading geotools integration 

### ISSUE THREAD

**Issue by geoHeil** [DataSystemsLab/GeoSpark#89]
Could you add shading for the company.vividsolution.jts used in geospark?
I plan to ist geospark and geotools in a project and their respective transitive dependencies collide for jts.

http://stackoverflow.com/questions/13620281/what-is-the-maven-shade-plugin-used-for-and-why-would-you-want-to-relocate-java provide a good overview why to shade such closely coupled internal dependencies.

**Comment by geoHeil** [comment]
https://github.com/geoHeil/GeoSpark/tree/shadingJTS here is a prototype built with the instructions of http://stackoverflow.com/questions/21021485/how-to-configure-maven-shade-plugin-in-a-multi-module-project 

Why did you not use the `parent pom` in the modules?

**Comment by geoHeil** [comment]
When not minimizing the resulting jar, the contents are fine. Whilst at it I would suggest to shade guava as well in order to not clash with i.e. geotools but mostly geospark

**Comment by jiayuasu** [comment]
Hi @geoHeil , thanks for your comments! You gave me lots of great suggestion.

I have several questions about this issue: 1. In the new PR, it seems you create another module to make the shading work. This module packaged all GeoSpark and Babylon together. This is not expected. I will update JTSplus repository to avoid this conflict. 2. I am not sure why Guava is packaged into GeoSpark. I think I should totally exclude it. Will this solve the Guava conflict?

**Comment by geoHeil** [comment]
@jiayuasu , to my knowledge there are 2-3 Problems

- JTS geospark is using JTSPlus which is a mashup of JTS and additional functionality
- guava, spark is using guava as well, this simply should be shaded
- Geotools C dependencies (JAI) are not included / not included in the right version. (very tricky) http://stackoverflow.com/questions/43910006/geotools-jai-fatjar-causing-problems-in-native-dependencies

What I want to achieve is: Read ESRi ASCII Grid files into geoSpark. Currently I use geotools to read the raster data and create polygons from it. 
When having both geospark and geotools in the project, the wrong dependencies are selected. However when shading is applied as outlined above it works.

But it only works if the right assembly strategy (fat-jar) is applied when creating the spark job: http://stackoverflow.com/questions/43910006/geotools-jai-fatjar-causing-problems-in-native-dependencies do you know why the `MergeStrategy.first` is working (but has the downside that you do not know what **first** will be. The more elaborate strategy does seem to fail.

**Comment by jiayuasu** [comment]
@geoHeil , I will do two things to help you out. 1. I will rename all JTSplus root package name. 2. Remove Guava dependency.

Guava dependency is introduced because GeoSpark 0.6.2 depends SerNetCDF which package lots of unrelated packages.

After this, I will push a snapshot version for you to test.

**Comment by jiayuasu** [comment]
@geoHeil , in GeoSpark 0.7.0, 

1. I have integrated the latest GeoTools (17.0) into GeoSpark. I also removed all duplicated classes under JTS root folder. Only JTSplus version JTS exists in GeoSpark fat jar.

2. I changed SerNetCDF to an optional dependency. Therefore, you won't see any unrelated libraries in the GeoSpark fat jar such as Guava.

Thanks,
Jia
